services:
  php:
    build:
      context: .
      target: dev
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
    container_name: jusprime_php_dev
    working_dir: /var/www
    environment:
      TZ: America/Sao_Paulo
      APP_ENV: dev
      APP_DEBUG: 1
    volumes:
      - .:/var/www
    networks:
      - saas_net

  nginx:
    image: nginx:alpine
    container_name: jusprime_nginx_dev
    volumes:
      - .:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - php
    networks:
      - saas_net

  db:
    image: postgres:15
    container_name: jusprime_db_dev
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-symfony}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-symfony}
      POSTGRES_DB: ${POSTGRES_DB:-saas}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - saas_net

networks:
  saas_net:

volumes:
  db_data:
