<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260509000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Etapa 5a: criar tabela invitation, adicionar oab_numero/oab_uf em user, converter invitation_token existentes';
    }

    public function up(Schema $schema): void
    {
        // ---- 1. Criar tabela invitation ----------------------------------------

        $this->addSql(<<<'SQL'
            CREATE TABLE IF NOT EXISTS invitation (
                id                  INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                email               VARCHAR(180)  NOT NULL,
                token               VARCHAR(64)   NOT NULL,
                type                VARCHAR(20)   NOT NULL,
                full_name           VARCHAR(255)  DEFAULT NULL,
                status              VARCHAR(20)   NOT NULL,
                created_at          TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                expires_at          TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                responded_at        TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                tenant_id           INT DEFAULT NULL,
                tenant_role_id      INT DEFAULT NULL,
                cargo_id            INT DEFAULT NULL,
                lotacao_id          INT DEFAULT NULL,
                created_by_id       INT DEFAULT NULL,
                accepted_as_user_id INT DEFAULT NULL,
                PRIMARY KEY (id),
                CONSTRAINT uq_invitation_token UNIQUE (token)
            )
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_invitation_email
                ON invitation (email)
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_invitation_status_expires
                ON invitation (status, expires_at)
        SQL);

        $this->addSql(<<<'SQL'
            CREATE INDEX IF NOT EXISTS idx_invitation_tenant_status
                ON invitation (tenant_id, status)
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE invitation
                ADD CONSTRAINT fk_invitation_tenant
                    FOREIGN KEY (tenant_id) REFERENCES tenant(id) ON DELETE SET NULL,
                ADD CONSTRAINT fk_invitation_tenant_role
                    FOREIGN KEY (tenant_role_id) REFERENCES tenant_role(id) ON DELETE SET NULL,
                ADD CONSTRAINT fk_invitation_cargo
                    FOREIGN KEY (cargo_id) REFERENCES cargo(id) ON DELETE SET NULL,
                ADD CONSTRAINT fk_invitation_lotacao
                    FOREIGN KEY (lotacao_id) REFERENCES lotacao(id) ON DELETE SET NULL,
                ADD CONSTRAINT fk_invitation_created_by
                    FOREIGN KEY (created_by_id) REFERENCES "user"(id) ON DELETE SET NULL,
                ADD CONSTRAINT fk_invitation_accepted_user
                    FOREIGN KEY (accepted_as_user_id) REFERENCES "user"(id) ON DELETE SET NULL
        SQL);

        // ---- 2. Adicionar colunas OAB em user ----------------------------------

        $this->addSql(<<<'SQL'
            ALTER TABLE "user"
                ADD COLUMN IF NOT EXISTS oab_numero VARCHAR(20) DEFAULT NULL,
                ADD COLUMN IF NOT EXISTS oab_uf     VARCHAR(2)  DEFAULT NULL
        SQL);

        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                BEGIN
                    ALTER TABLE "user"
                        ADD CONSTRAINT chk_user_oab_uf
                            CHECK (oab_uf IS NULL OR oab_uf ~ '^[A-Z]{2}$');
                EXCEPTION WHEN duplicate_object THEN NULL;
                END;

                BEGIN
                    ALTER TABLE "user"
                        ADD CONSTRAINT chk_user_oab_numero
                            CHECK (oab_numero IS NULL OR oab_numero ~ '^[0-9]+$');
                EXCEPTION WHEN duplicate_object THEN NULL;
                END;
            END $$
        SQL);

        // ---- 3. Converter invitation_token existentes --------------------------

        // Aviso nos logs se não houver SuperAdmin (não bloqueia a migration)
        $this->addSql(<<<'SQL'
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM "user" WHERE roles::jsonb @> '"ROLE_SUPER_ADMIN"'::jsonb
                ) THEN
                    RAISE NOTICE 'AVISO: Nenhum usuário com ROLE_SUPER_ADMIN encontrado. Convites convertidos ficarão com created_by_id = NULL.';
                END IF;
            END $$
        SQL);

        $this->addSql(<<<'SQL'
            INSERT INTO invitation (
                email, token, type, tenant_id, status, created_by_id, created_at, expires_at
            )
            SELECT
                u.email,
                u.invitation_token,
                'escritorio',
                u.tenant_id,
                'expired',
                (SELECT id FROM "user" WHERE roles::jsonb @> '"ROLE_SUPER_ADMIN"'::jsonb ORDER BY id LIMIT 1),
                u.created_at,
                NOW()
            FROM "user" u
            WHERE u.invitation_token IS NOT NULL
              AND NOT EXISTS (
                  SELECT 1 FROM invitation i WHERE i.token = u.invitation_token
              )
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS invitation');

        $this->addSql(<<<'SQL'
            ALTER TABLE "user"
                DROP CONSTRAINT IF EXISTS chk_user_oab_uf,
                DROP CONSTRAINT IF EXISTS chk_user_oab_numero,
                DROP COLUMN IF EXISTS oab_numero,
                DROP COLUMN IF EXISTS oab_uf
        SQL);
    }
}
