<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260422123639 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adicionar tabelas jornada_tenant, bloco_jornada, bloco_escala_usuario e coluna carga_horaria_semanal em escala_trabalho';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE bloco_escala_usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dias_semana JSON NOT NULL, entrada VARCHAR(5) NOT NULL, repouso VARCHAR(5) DEFAULT NULL, retorno VARCHAR(5) DEFAULT NULL, saida VARCHAR(5) NOT NULL, minutos_bloco INT NOT NULL, escala_trabalho_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4F31C3B9E78B85AF ON bloco_escala_usuario (escala_trabalho_id)');
        $this->addSql('CREATE TABLE bloco_jornada (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dias_semana JSON NOT NULL, entrada VARCHAR(5) NOT NULL, repouso VARCHAR(5) DEFAULT NULL, retorno VARCHAR(5) DEFAULT NULL, saida VARCHAR(5) NOT NULL, minutos_bloco INT NOT NULL, jornada_tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_461DB94D815FD7D6 ON bloco_jornada (jornada_tenant_id)');
        $this->addSql('CREATE TABLE jornada_tenant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, carga_horaria_semanal INT NOT NULL, alerta_habilitado BOOLEAN NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_65EC62179033212A ON jornada_tenant (tenant_id)');
        $this->addSql('ALTER TABLE bloco_escala_usuario ADD CONSTRAINT FK_4F31C3B9E78B85AF FOREIGN KEY (escala_trabalho_id) REFERENCES escala_trabalho (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE bloco_jornada ADD CONSTRAINT FK_461DB94D815FD7D6 FOREIGN KEY (jornada_tenant_id) REFERENCES jornada_tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE jornada_tenant ADD CONSTRAINT FK_65EC62179033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE escala_trabalho ADD carga_horaria_semanal INT DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE bloco_escala_usuario DROP CONSTRAINT FK_4F31C3B9E78B85AF');
        $this->addSql('ALTER TABLE bloco_jornada DROP CONSTRAINT FK_461DB94D815FD7D6');
        $this->addSql('ALTER TABLE jornada_tenant DROP CONSTRAINT FK_65EC62179033212A');
        $this->addSql('DROP TABLE bloco_escala_usuario');
        $this->addSql('DROP TABLE bloco_jornada');
        $this->addSql('DROP TABLE jornada_tenant');
        $this->addSql('ALTER TABLE escala_trabalho DROP carga_horaria_semanal');
    }
}
