<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Permite vincular vários processos a uma pasta (com um principal).
 *
 * Substitui o vínculo 1:1 pasta.processo_id por uma tabela de associação pasta_processo
 * (pasta + processo + flag principal). Faz backfill: cada pasta com processo_id vira uma
 * linha marcada como principal. Só então dropa a coluna antiga.
 */
final class Version20260630210213 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Vincula vários processos a uma pasta (tabela pasta_processo com principal); backfill do processo_id atual como principal';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pasta_processo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, principal BOOLEAN DEFAULT false NOT NULL, vinculado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pasta_id INT NOT NULL, processo_id INT NOT NULL, vinculado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_15973D817FCDBC8C ON pasta_processo (pasta_id)');
        $this->addSql('CREATE INDEX IDX_15973D81AAA822D2 ON pasta_processo (processo_id)');
        $this->addSql('CREATE INDEX IDX_15973D81EDD250C1 ON pasta_processo (vinculado_por_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pasta_processo ON pasta_processo (pasta_id, processo_id)');
        $this->addSql('ALTER TABLE pasta_processo ADD CONSTRAINT FK_15973D817FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_processo ADD CONSTRAINT FK_15973D81AAA822D2 FOREIGN KEY (processo_id) REFERENCES processo (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_processo ADD CONSTRAINT FK_15973D81EDD250C1 FOREIGN KEY (vinculado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');

        // Backfill: o processo atual de cada pasta passa a ser o vínculo principal.
        $this->addSql('INSERT INTO pasta_processo (pasta_id, processo_id, principal, vinculado_em) SELECT id, processo_id, true, NOW() FROM pasta WHERE processo_id IS NOT NULL');

        $this->addSql('ALTER TABLE pasta DROP CONSTRAINT fk_9b3bbc81aaa822d2');
        $this->addSql('DROP INDEX idx_9b3bbc81aaa822d2');
        $this->addSql('ALTER TABLE pasta DROP processo_id');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pasta ADD processo_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pasta ADD CONSTRAINT fk_9b3bbc81aaa822d2 FOREIGN KEY (processo_id) REFERENCES processo (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_9b3bbc81aaa822d2 ON pasta (processo_id)');

        // Restaura o processo principal como o único vínculo da pasta antes de dropar a tabela.
        $this->addSql('UPDATE pasta SET processo_id = (SELECT pp.processo_id FROM pasta_processo pp WHERE pp.pasta_id = pasta.id AND pp.principal = true ORDER BY pp.id ASC LIMIT 1)');

        $this->addSql('ALTER TABLE pasta_processo DROP CONSTRAINT FK_15973D817FCDBC8C');
        $this->addSql('ALTER TABLE pasta_processo DROP CONSTRAINT FK_15973D81AAA822D2');
        $this->addSql('ALTER TABLE pasta_processo DROP CONSTRAINT FK_15973D81EDD250C1');
        $this->addSql('DROP TABLE pasta_processo');
    }
}
