<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328182446 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Dia 11 — Cria tabela resource_access para controle granular por item (cliente/pasta/processo)';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE resource_access (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, resource_type VARCHAR(50) NOT NULL, resource_id INT NOT NULL, can_view BOOLEAN DEFAULT false NOT NULL, can_edit BOOLEAN DEFAULT false NOT NULL, can_delete BOOLEAN DEFAULT false NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_id INT NOT NULL, granted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_CE95C1AEA76ED395 ON resource_access (user_id)');
        $this->addSql('CREATE INDEX IDX_CE95C1AE3151C11F ON resource_access (granted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_resource_access_user_resource ON resource_access (user_id, resource_type, resource_id)');
        $this->addSql('ALTER TABLE resource_access ADD CONSTRAINT FK_CE95C1AEA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE resource_access ADD CONSTRAINT FK_CE95C1AE3151C11F FOREIGN KEY (granted_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE resource_access DROP CONSTRAINT FK_CE95C1AEA76ED395');
        $this->addSql('ALTER TABLE resource_access DROP CONSTRAINT FK_CE95C1AE3151C11F');
        $this->addSql('DROP TABLE resource_access');
    }
}
