<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260623174937 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria tabela aceite_termo (registro versionado de aceite dos Termos de Uso)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE aceite_termo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, versao VARCHAR(40) NOT NULL, aceito_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ip VARCHAR(45) NOT NULL, user_agent TEXT DEFAULT NULL, user_id INT NOT NULL, tenant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_90D73CD3A76ED395 ON aceite_termo (user_id)');
        $this->addSql('CREATE INDEX IDX_90D73CD39033212A ON aceite_termo (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_aceite_termo_user_versao ON aceite_termo (user_id, versao)');
        $this->addSql('ALTER TABLE aceite_termo ADD CONSTRAINT FK_90D73CD3A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE aceite_termo ADD CONSTRAINT FK_90D73CD39033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE aceite_termo DROP CONSTRAINT FK_90D73CD3A76ED395');
        $this->addSql('ALTER TABLE aceite_termo DROP CONSTRAINT FK_90D73CD39033212A');
        $this->addSql('DROP TABLE aceite_termo');
    }
}
