<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328173417 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, code VARCHAR(100) NOT NULL, description VARCHAR(255) NOT NULL, "group" VARCHAR(50) NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E04992AA77153098 ON permission (code)');
        $this->addSql('CREATE TABLE tenant_role (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(100) NOT NULL, description VARCHAR(255) DEFAULT NULL, is_system BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1D06D0B99033212A ON tenant_role (tenant_id)');
        $this->addSql('CREATE TABLE tenant_role_permission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, granted_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_role_id INT NOT NULL, permission_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_6C71F0EDC4956098 ON tenant_role_permission (tenant_role_id)');
        $this->addSql('CREATE INDEX IDX_6C71F0EDFED90CCA ON tenant_role_permission (permission_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_tenant_role_permission ON tenant_role_permission (tenant_role_id, permission_id)');
        $this->addSql('ALTER TABLE tenant_role ADD CONSTRAINT FK_1D06D0B99033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tenant_role_permission ADD CONSTRAINT FK_6C71F0EDC4956098 FOREIGN KEY (tenant_role_id) REFERENCES tenant_role (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tenant_role_permission ADD CONSTRAINT FK_6C71F0EDFED90CCA FOREIGN KEY (permission_id) REFERENCES permission (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE evento ALTER visibilidade DROP DEFAULT');
        $this->addSql('ALTER TABLE "user" ADD tenant_role_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649C4956098 FOREIGN KEY (tenant_role_id) REFERENCES tenant_role (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8D93D649C4956098 ON "user" (tenant_role_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tenant_role DROP CONSTRAINT FK_1D06D0B99033212A');
        $this->addSql('ALTER TABLE tenant_role_permission DROP CONSTRAINT FK_6C71F0EDC4956098');
        $this->addSql('ALTER TABLE tenant_role_permission DROP CONSTRAINT FK_6C71F0EDFED90CCA');
        $this->addSql('DROP TABLE permission');
        $this->addSql('DROP TABLE tenant_role');
        $this->addSql('DROP TABLE tenant_role_permission');
        $this->addSql('ALTER TABLE evento ALTER visibilidade SET DEFAULT \'todos\'');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649C4956098');
        $this->addSql('DROP INDEX IDX_8D93D649C4956098');
        $this->addSql('ALTER TABLE "user" DROP tenant_role_id');
    }
}
