<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Pagamentos a receber da pasta — fatia 2 do redesenho da pasta_show
 * (`docs/specs/pasta-show-financeiro-fatia2.md`).
 *
 * Tabela nova, nada de dado existente é tocado: hoje o que o cliente combinou
 * pagar por um caso vive em texto livre (2 observações financeiras em toda a
 * produção) ou fora do sistema.
 *
 * Não confundir com a Cobrança: lá o dinheiro é a dívida de um devedor numa
 * carteira; aqui é o que o escritório tem a receber pelo caso. Por isso a
 * tabela é da Pasta e não tem ligação nenhuma com `cobranca_*`.
 *
 * O ESTADO NÃO TEM COLUNA: `pago_em` preenchido é pago, vazio com vencimento no
 * passado é vencido. Uma coluna de status poderia divergir da data.
 *
 * O `--dump-sql` desta base também propunha, por ruído alheio a esta frente,
 * `DROP INDEX` em três índices FUNCIONAIS (`uniq_cobranca_obrigacao_ref_competencia`,
 * `idx_cobranca_pessoa_tenant_cpf_digitos`, `idx_cobranca_pessoa_tenant_cnpj_digitos`)
 * e `DROP DEFAULT` em colunas de `cobranca_pessoa_*`. Nada disso entrou aqui: o
 * Doctrine não sabe representar índice funcional no mapeamento e propõe apagá-lo.
 */
final class Version20260828190000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria pasta_pagamento: o que o cliente combinou pagar pelo caso.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE pasta_pagamento (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                descricao VARCHAR(120) NOT NULL,
                valor NUMERIC(15, 2) NOT NULL,
                vencimento DATE NOT NULL,
                pago_em DATE DEFAULT NULL,
                criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                pasta_id INT NOT NULL,
                tenant_id INT NOT NULL,
                autor_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX IDX_E17CD65014D45BBE ON pasta_pagamento (autor_id)');
        $this->addSql('CREATE INDEX idx_pasta_pagamento_pasta_id ON pasta_pagamento (pasta_id)');
        $this->addSql('CREATE INDEX idx_pasta_pagamento_tenant ON pasta_pagamento (tenant_id)');
        $this->addSql('CREATE INDEX idx_pasta_pagamento_vencimento ON pasta_pagamento (vencimento)');

        // Excluir a pasta leva os pagamentos junto; excluir o usuário só apaga a
        // autoria, nunca o lançamento — o dinheiro não é dele, é da pasta.
        $this->addSql('ALTER TABLE pasta_pagamento ADD CONSTRAINT FK_E17CD6507FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pasta_pagamento ADD CONSTRAINT FK_E17CD6509033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE pasta_pagamento ADD CONSTRAINT FK_E17CD65014D45BBE FOREIGN KEY (autor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE pasta_pagamento');
    }
}
