<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * M2 da aba Documentos (D2, DOC-23): favoritos (estrela) de arquivo e de subpasta, por usuário.
 *
 * Escrita à mão, só com a tabela desta frente. Índices e uniques com os nomes declarados em
 * `App\Pasta\Entity\PastaDocumentoFavorito`; FKs pelo hash padrão do DBAL (`FK_` + crc32 da tabela
 * e da coluna — conferido contra o precedente `pasta_favorita`), para o `doctrine:schema:validate`
 * não propor nada.
 *
 * Anatomia:
 *   - CHECK `chk_pasta_documento_favorito_um_alvo`: exatamente um de `documento_id`/`secao_id`
 *     (o Doctrine não mapeia CHECK; o schema:validate não o enxerga e não o propõe apagar);
 *   - UNIQUE (user_id, documento_id) e (user_id, secao_id): NULL não colide em índice único no
 *     PostgreSQL, então não é preciso índice parcial;
 *   - `documento_id`/`secao_id`/`user_id` CASCADE; `tenant_id` sem ação (a purga apaga
 *     explicitamente, `PurgarEscritorioUseCase::ORDEM_DELECAO`).
 *
 * Índices implícitos de FK não são criados: `tenant_id` é coberto por `(tenant_id, user_id)`,
 * `user_id` pelos uniques, `documento_id` e `secao_id` pelos índices próprios.
 */
final class Version20261007010000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria pasta_documento_favorito: estrela de arquivo/subpasta por usuário (aba Documentos, D2)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pasta_documento_favorito (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, user_id INT NOT NULL, documento_id INT DEFAULT NULL, secao_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_pasta_documento_favorito_tenant_user ON pasta_documento_favorito (tenant_id, user_id)');
        $this->addSql('CREATE INDEX idx_pasta_documento_favorito_documento ON pasta_documento_favorito (documento_id)');
        $this->addSql('CREATE INDEX idx_pasta_documento_favorito_secao ON pasta_documento_favorito (secao_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pasta_documento_favorito_user_documento ON pasta_documento_favorito (user_id, documento_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pasta_documento_favorito_user_secao ON pasta_documento_favorito (user_id, secao_id)');
        $this->addSql('ALTER TABLE pasta_documento_favorito ADD CONSTRAINT chk_pasta_documento_favorito_um_alvo CHECK (num_nonnulls(documento_id, secao_id) = 1)');
        $this->addSql('ALTER TABLE pasta_documento_favorito ADD CONSTRAINT FK_9C20AB119033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_documento_favorito ADD CONSTRAINT FK_9C20AB11A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_documento_favorito ADD CONSTRAINT FK_9C20AB1145C0CF75 FOREIGN KEY (documento_id) REFERENCES pasta_documento (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_documento_favorito ADD CONSTRAINT FK_9C20AB114E04F226 FOREIGN KEY (secao_id) REFERENCES pasta_secao (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pasta_documento_favorito DROP CONSTRAINT FK_9C20AB119033212A');
        $this->addSql('ALTER TABLE pasta_documento_favorito DROP CONSTRAINT FK_9C20AB11A76ED395');
        $this->addSql('ALTER TABLE pasta_documento_favorito DROP CONSTRAINT FK_9C20AB1145C0CF75');
        $this->addSql('ALTER TABLE pasta_documento_favorito DROP CONSTRAINT FK_9C20AB114E04F226');
        $this->addSql('DROP TABLE pasta_documento_favorito');
    }
}
