<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709142845 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cobranças Etapa 3 — pagamentos e liquidações: tabelas cobranca_pagamento '
            . '(composição dívida/encargos/honorários em centavos INT), cobranca_alocacao_pagamento '
            . '(quanto de cada pagamento abateu cada obrigação — invariável 12) e cobranca_liquidacao '
            . '(valor reconhecido reduz o saldo, distinto do valor do bem), todas escopadas por tenant.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cobranca_alocacao_pagamento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, valor INT NOT NULL, tenant_id INT NOT NULL, pagamento_id INT NOT NULL, obrigacao_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_867589259033212A ON cobranca_alocacao_pagamento (tenant_id)');
        $this->addSql('CREATE INDEX IDX_86758925E06F81F7 ON cobranca_alocacao_pagamento (pagamento_id)');
        $this->addSql('CREATE INDEX idx_cobranca_alocacao_tenant_pagamento ON cobranca_alocacao_pagamento (tenant_id, pagamento_id)');
        $this->addSql('CREATE INDEX idx_cobranca_alocacao_obrigacao ON cobranca_alocacao_pagamento (obrigacao_id)');
        $this->addSql('CREATE TABLE cobranca_liquidacao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(255) NOT NULL, descricao_bem VARCHAR(255) NOT NULL, valor_atribuido_bem INT DEFAULT NULL, valor_reconhecido INT NOT NULL, data DATE NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, caso_id INT NOT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_656AE26A9033212A ON cobranca_liquidacao (tenant_id)');
        $this->addSql('CREATE INDEX IDX_656AE26AA0AD3491 ON cobranca_liquidacao (caso_id)');
        $this->addSql('CREATE INDEX IDX_656AE26AF42F4A03 ON cobranca_liquidacao (criado_por_id)');
        $this->addSql('CREATE INDEX idx_cobranca_liquidacao_tenant_caso ON cobranca_liquidacao (tenant_id, caso_id)');
        $this->addSql('CREATE TABLE cobranca_pagamento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data DATE NOT NULL, valor_divida INT DEFAULT 0 NOT NULL, valor_encargos INT DEFAULT 0 NOT NULL, valor_honorarios INT DEFAULT 0 NOT NULL, motivo_correcao VARCHAR(255) DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, caso_id INT NOT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7452B0B19033212A ON cobranca_pagamento (tenant_id)');
        $this->addSql('CREATE INDEX IDX_7452B0B1A0AD3491 ON cobranca_pagamento (caso_id)');
        $this->addSql('CREATE INDEX IDX_7452B0B1F42F4A03 ON cobranca_pagamento (criado_por_id)');
        $this->addSql('CREATE INDEX idx_cobranca_pagamento_tenant_caso ON cobranca_pagamento (tenant_id, caso_id)');
        $this->addSql('ALTER TABLE cobranca_alocacao_pagamento ADD CONSTRAINT FK_867589259033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_alocacao_pagamento ADD CONSTRAINT FK_86758925E06F81F7 FOREIGN KEY (pagamento_id) REFERENCES cobranca_pagamento (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_alocacao_pagamento ADD CONSTRAINT FK_86758925C4F4E38 FOREIGN KEY (obrigacao_id) REFERENCES cobranca_obrigacao (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_liquidacao ADD CONSTRAINT FK_656AE26A9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_liquidacao ADD CONSTRAINT FK_656AE26AA0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_liquidacao ADD CONSTRAINT FK_656AE26AF42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_pagamento ADD CONSTRAINT FK_7452B0B19033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_pagamento ADD CONSTRAINT FK_7452B0B1A0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_pagamento ADD CONSTRAINT FK_7452B0B1F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cobranca_alocacao_pagamento DROP CONSTRAINT FK_867589259033212A');
        $this->addSql('ALTER TABLE cobranca_alocacao_pagamento DROP CONSTRAINT FK_86758925E06F81F7');
        $this->addSql('ALTER TABLE cobranca_alocacao_pagamento DROP CONSTRAINT FK_86758925C4F4E38');
        $this->addSql('ALTER TABLE cobranca_liquidacao DROP CONSTRAINT FK_656AE26A9033212A');
        $this->addSql('ALTER TABLE cobranca_liquidacao DROP CONSTRAINT FK_656AE26AA0AD3491');
        $this->addSql('ALTER TABLE cobranca_liquidacao DROP CONSTRAINT FK_656AE26AF42F4A03');
        $this->addSql('ALTER TABLE cobranca_pagamento DROP CONSTRAINT FK_7452B0B19033212A');
        $this->addSql('ALTER TABLE cobranca_pagamento DROP CONSTRAINT FK_7452B0B1A0AD3491');
        $this->addSql('ALTER TABLE cobranca_pagamento DROP CONSTRAINT FK_7452B0B1F42F4A03');
        $this->addSql('DROP TABLE cobranca_alocacao_pagamento');
        $this->addSql('DROP TABLE cobranca_liquidacao');
        $this->addSql('DROP TABLE cobranca_pagamento');
    }
}
