<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260317164135 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER INDEX idx_5e3005efaa822d2 RENAME TO IDX_5C3254B278217710');
        $this->addSql('ALTER INDEX idx_5e3005effb88e14f RENAME TO IDX_5C3254B2DB38439E');
        $this->addSql('ALTER TABLE audit_log ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE audit_log ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE chamado DROP CONSTRAINT fk_chamado_solicitante');
        $this->addSql('ALTER TABLE chamado DROP CONSTRAINT fk_chamado_responsavel');
        $this->addSql('DROP INDEX idx_chamado_categoria');
        $this->addSql('DROP INDEX idx_chamado_criado_em');
        $this->addSql('DROP INDEX idx_chamado_prioridade');
        $this->addSql('DROP INDEX idx_chamado_status');
        $this->addSql('ALTER TABLE chamado ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chamado ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE chamado ALTER categoria DROP DEFAULT');
        $this->addSql('ALTER TABLE chamado ALTER prioridade DROP DEFAULT');
        $this->addSql('ALTER TABLE chamado ALTER status DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN chamado.criado_em IS \'\'');
        $this->addSql('COMMENT ON COLUMN chamado.atualizado_em IS \'\'');
        $this->addSql('COMMENT ON COLUMN chamado.resolvido_em IS \'\'');
        $this->addSql('COMMENT ON COLUMN chamado.fechado_em IS \'\'');
        $this->addSql('ALTER TABLE chamado ADD CONSTRAINT FK_3B02066FC680A87 FOREIGN KEY (solicitante_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE chamado ADD CONSTRAINT FK_3B02066FBB9AF004 FOREIGN KEY (responsavel_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_chamado_solicitante RENAME TO IDX_3B02066FC680A87');
        $this->addSql('ALTER INDEX idx_chamado_responsavel RENAME TO IDX_3B02066FBB9AF004');
        $this->addSql('ALTER TABLE chamado_anexo DROP CONSTRAINT fk_chamado_anexo_usuario');
        $this->addSql('DROP INDEX idx_chamado_anexo_usuario');
        $this->addSql('ALTER TABLE chamado_anexo ADD enviado_por_id INT NOT NULL');
        $this->addSql('ALTER TABLE chamado_anexo DROP usuario_id');
        $this->addSql('ALTER TABLE chamado_anexo ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chamado_anexo ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('COMMENT ON COLUMN chamado_anexo.criado_em IS \'\'');
        $this->addSql('ALTER TABLE chamado_anexo ADD CONSTRAINT FK_B393C96566B4CF03 FOREIGN KEY (enviado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_B393C96566B4CF03 ON chamado_anexo (enviado_por_id)');
        $this->addSql('ALTER INDEX idx_chamado_anexo_chamado RENAME TO IDX_B393C9659D9E8FBC');
        $this->addSql('ALTER TABLE chamado_interacao DROP CONSTRAINT fk_chamado_interacao_usuario');
        $this->addSql('DROP INDEX idx_chamado_interacao_usuario');
        $this->addSql('DROP INDEX idx_chamado_interacao_tipo');
        $this->addSql('DROP INDEX idx_chamado_interacao_criado_em');
        $this->addSql('ALTER TABLE chamado_interacao ADD autor_id INT NOT NULL');
        $this->addSql('ALTER TABLE chamado_interacao DROP usuario_id');
        $this->addSql('ALTER TABLE chamado_interacao ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE chamado_interacao ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE chamado_interacao ALTER tipo TYPE VARCHAR(30)');
        $this->addSql('ALTER TABLE chamado_interacao ALTER tipo DROP DEFAULT');
        $this->addSql('ALTER TABLE chamado_interacao ALTER interno DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN chamado_interacao.criado_em IS \'\'');
        $this->addSql('ALTER TABLE chamado_interacao ADD CONSTRAINT FK_8E6FFA2914D45BBE FOREIGN KEY (autor_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8E6FFA2914D45BBE ON chamado_interacao (autor_id)');
        $this->addSql('ALTER INDEX idx_chamado_interacao_chamado RENAME TO IDX_8E6FFA299D9E8FBC');
        $this->addSql('ALTER TABLE contrato ADD titulo VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE contrato ADD descricao TEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE contrato DROP nome_arquivo');
        $this->addSql('ALTER TABLE contrato DROP caminho_arquivo');
        $this->addSql('ALTER INDEX idx_3d3ae85853c59d72 RENAME TO IDX_66696523BB9AF004');
        $this->addSql('ALTER TABLE documento_processo ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE documento_processo ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER INDEX idx_1418d2e13474f1a RENAME TO IDX_42EE57D4AAA822D2');
        $this->addSql('ALTER TABLE evento DROP CONSTRAINT fk_evento_criador');
        $this->addSql('DROP INDEX idx_evento_data_inicio');
        $this->addSql('DROP INDEX idx_evento_status');
        $this->addSql('ALTER TABLE evento ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE evento ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE evento ALTER status DROP DEFAULT');
        $this->addSql('ALTER TABLE evento ALTER cor DROP DEFAULT');
        $this->addSql('ALTER TABLE evento ALTER dia_inteiro DROP DEFAULT');
        $this->addSql('ALTER TABLE evento ALTER recorrente DROP DEFAULT');
        $this->addSql('COMMENT ON COLUMN evento.data_inicio IS \'\'');
        $this->addSql('COMMENT ON COLUMN evento.data_fim IS \'\'');
        $this->addSql('COMMENT ON COLUMN evento.fim_recorrencia IS \'\'');
        $this->addSql('COMMENT ON COLUMN evento.criado_em IS \'\'');
        $this->addSql('COMMENT ON COLUMN evento.modificado_em IS \'\'');
        $this->addSql('ALTER TABLE evento ADD CONSTRAINT FK_47860B05355B1972 FOREIGN KEY (criador_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER INDEX idx_evento_criador RENAME TO IDX_47860B05355B1972');
        $this->addSql('ALTER INDEX idx_evento_participante_evento RENAME TO IDX_5069537287A5F842');
        $this->addSql('ALTER INDEX idx_evento_participante_user RENAME TO IDX_50695372A76ED395');
        $this->addSql('ALTER TABLE legenda_cor ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE legenda_cor ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('DROP INDEX idx_notificacao_criada_em');
        $this->addSql('DROP INDEX idx_notificacao_lida');
        $this->addSql('ALTER TABLE notificacao ALTER id DROP DEFAULT');
        $this->addSql('ALTER TABLE notificacao ALTER id ADD GENERATED BY DEFAULT AS IDENTITY');
        $this->addSql('ALTER TABLE notificacao ALTER lida DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_notificacao_usuario RENAME TO IDX_5ACD9386DB38439E');
        $this->addSql('ALTER TABLE processo ALTER status_documentos DROP DEFAULT');
        $this->addSql('ALTER INDEX idx_processo_pai_id RENAME TO IDX_16E5B82DF51A381F');
        $this->addSql('ALTER INDEX idx_5a86847faa822d2 RENAME TO IDX_31B4CBAAAA822D2');
        $this->addSql('ALTER INDEX idx_tarefa_mensagem_tarefa RENAME TO IDX_F0B050EB78217710');
        $this->addSql('ALTER INDEX idx_tarefa_mensagem_usuario RENAME TO IDX_F0B050EBDB38439E');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER INDEX idx_5c3254b2db38439e RENAME TO idx_5e3005effb88e14f');
        $this->addSql('ALTER INDEX idx_5c3254b278217710 RENAME TO idx_5e3005efaa822d2');
        $this->addSql('ALTER TABLE audit_log ALTER id SET DEFAULT nextval(\'audit_log_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE audit_log ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE chamado DROP CONSTRAINT FK_3B02066FC680A87');
        $this->addSql('ALTER TABLE chamado DROP CONSTRAINT FK_3B02066FBB9AF004');
        $this->addSql('ALTER TABLE chamado ALTER id SET DEFAULT nextval(\'chamado_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chamado ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE chamado ALTER categoria SET DEFAULT \'outros\'');
        $this->addSql('ALTER TABLE chamado ALTER prioridade SET DEFAULT \'media\'');
        $this->addSql('ALTER TABLE chamado ALTER status SET DEFAULT \'aberto\'');
        $this->addSql('COMMENT ON COLUMN chamado.criado_em IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chamado.atualizado_em IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chamado.resolvido_em IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN chamado.fechado_em IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE chamado ADD CONSTRAINT fk_chamado_solicitante FOREIGN KEY (solicitante_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE chamado ADD CONSTRAINT fk_chamado_responsavel FOREIGN KEY (responsavel_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_chamado_categoria ON chamado (categoria)');
        $this->addSql('CREATE INDEX idx_chamado_criado_em ON chamado (criado_em)');
        $this->addSql('CREATE INDEX idx_chamado_prioridade ON chamado (prioridade)');
        $this->addSql('CREATE INDEX idx_chamado_status ON chamado (status)');
        $this->addSql('ALTER INDEX idx_3b02066fbb9af004 RENAME TO idx_chamado_responsavel');
        $this->addSql('ALTER INDEX idx_3b02066fc680a87 RENAME TO idx_chamado_solicitante');
        $this->addSql('ALTER TABLE chamado_anexo DROP CONSTRAINT FK_B393C96566B4CF03');
        $this->addSql('DROP INDEX IDX_B393C96566B4CF03');
        $this->addSql('ALTER TABLE chamado_anexo ADD usuario_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE chamado_anexo DROP enviado_por_id');
        $this->addSql('ALTER TABLE chamado_anexo ALTER id SET DEFAULT nextval(\'chamado_anexo_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chamado_anexo ALTER id DROP IDENTITY');
        $this->addSql('COMMENT ON COLUMN chamado_anexo.criado_em IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE chamado_anexo ADD CONSTRAINT fk_chamado_anexo_usuario FOREIGN KEY (usuario_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_chamado_anexo_usuario ON chamado_anexo (usuario_id)');
        $this->addSql('ALTER INDEX idx_b393c9659d9e8fbc RENAME TO idx_chamado_anexo_chamado');
        $this->addSql('ALTER TABLE chamado_interacao DROP CONSTRAINT FK_8E6FFA2914D45BBE');
        $this->addSql('DROP INDEX IDX_8E6FFA2914D45BBE');
        $this->addSql('ALTER TABLE chamado_interacao ADD usuario_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE chamado_interacao DROP autor_id');
        $this->addSql('ALTER TABLE chamado_interacao ALTER id SET DEFAULT nextval(\'chamado_interacao_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE chamado_interacao ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE chamado_interacao ALTER tipo TYPE VARCHAR(50)');
        $this->addSql('ALTER TABLE chamado_interacao ALTER tipo SET DEFAULT \'comentario\'');
        $this->addSql('ALTER TABLE chamado_interacao ALTER interno SET DEFAULT false');
        $this->addSql('COMMENT ON COLUMN chamado_interacao.criado_em IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE chamado_interacao ADD CONSTRAINT fk_chamado_interacao_usuario FOREIGN KEY (usuario_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_chamado_interacao_usuario ON chamado_interacao (usuario_id)');
        $this->addSql('CREATE INDEX idx_chamado_interacao_tipo ON chamado_interacao (tipo)');
        $this->addSql('CREATE INDEX idx_chamado_interacao_criado_em ON chamado_interacao (criado_em)');
        $this->addSql('ALTER INDEX idx_8e6ffa299d9e8fbc RENAME TO idx_chamado_interacao_chamado');
        $this->addSql('ALTER TABLE contrato ADD caminho_arquivo VARCHAR(255) NOT NULL');
        $this->addSql('ALTER TABLE contrato DROP descricao');
        $this->addSql('ALTER TABLE contrato RENAME COLUMN titulo TO nome_arquivo');
        $this->addSql('ALTER INDEX idx_66696523bb9af004 RENAME TO idx_3d3ae85853c59d72');
        $this->addSql('ALTER TABLE documento_processo ALTER id SET DEFAULT nextval(\'documento_processo_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE documento_processo ALTER id DROP IDENTITY');
        $this->addSql('ALTER INDEX idx_42ee57d4aaa822d2 RENAME TO idx_1418d2e13474f1a');
        $this->addSql('ALTER TABLE evento DROP CONSTRAINT FK_47860B05355B1972');
        $this->addSql('ALTER TABLE evento ALTER id SET DEFAULT nextval(\'evento_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE evento ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE evento ALTER status SET DEFAULT \'agendado\'');
        $this->addSql('ALTER TABLE evento ALTER cor SET DEFAULT \'#0073b7\'');
        $this->addSql('ALTER TABLE evento ALTER dia_inteiro SET DEFAULT false');
        $this->addSql('ALTER TABLE evento ALTER recorrente SET DEFAULT false');
        $this->addSql('COMMENT ON COLUMN evento.data_inicio IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN evento.data_fim IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN evento.fim_recorrencia IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN evento.criado_em IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN evento.modificado_em IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE evento ADD CONSTRAINT fk_evento_criador FOREIGN KEY (criador_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_evento_data_inicio ON evento (data_inicio)');
        $this->addSql('CREATE INDEX idx_evento_status ON evento (status)');
        $this->addSql('ALTER INDEX idx_47860b05355b1972 RENAME TO idx_evento_criador');
        $this->addSql('ALTER INDEX idx_5069537287a5f842 RENAME TO idx_evento_participante_evento');
        $this->addSql('ALTER INDEX idx_50695372a76ed395 RENAME TO idx_evento_participante_user');
        $this->addSql('ALTER TABLE legenda_cor ALTER id SET DEFAULT nextval(\'legenda_cor_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE legenda_cor ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE notificacao ALTER id SET DEFAULT nextval(\'notificacao_id_seq\'::regclass)');
        $this->addSql('ALTER TABLE notificacao ALTER id DROP IDENTITY');
        $this->addSql('ALTER TABLE notificacao ALTER lida SET DEFAULT false');
        $this->addSql('CREATE INDEX idx_notificacao_criada_em ON notificacao (criada_em)');
        $this->addSql('CREATE INDEX idx_notificacao_lida ON notificacao (lida)');
        $this->addSql('ALTER INDEX idx_5acd9386db38439e RENAME TO idx_notificacao_usuario');
        $this->addSql('ALTER TABLE processo ALTER status_documentos SET DEFAULT \'PENDENTE_DE_DOCUMENTACAO\'');
        $this->addSql('ALTER INDEX idx_16e5b82df51a381f RENAME TO idx_processo_pai_id');
        $this->addSql('ALTER INDEX idx_31b4cbaaaa822d2 RENAME TO idx_5a86847faa822d2');
        $this->addSql('ALTER INDEX idx_f0b050ebdb38439e RENAME TO idx_tarefa_mensagem_usuario');
        $this->addSql('ALTER INDEX idx_f0b050eb78217710 RENAME TO idx_tarefa_mensagem_tarefa');
    }
}
