<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260703165828 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Fase 2 captura total Datajud: tabela assunto_processo (todos os assuntos do processo, por tenant)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE assunto_processo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, codigo INT DEFAULT NULL, processo_id INT NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2C3E96E6AAA822D2 ON assunto_processo (processo_id)');
        $this->addSql('CREATE INDEX IDX_2C3E96E69033212A ON assunto_processo (tenant_id)');
        $this->addSql('ALTER TABLE assunto_processo ADD CONSTRAINT FK_2C3E96E6AAA822D2 FOREIGN KEY (processo_id) REFERENCES processo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE assunto_processo ADD CONSTRAINT FK_2C3E96E69033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE assunto_processo DROP CONSTRAINT FK_2C3E96E6AAA822D2');
        $this->addSql('ALTER TABLE assunto_processo DROP CONSTRAINT FK_2C3E96E69033212A');
        $this->addSql('DROP TABLE assunto_processo');
    }
}
