<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222153000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE processo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, contrato_id INT NOT NULL, numero_processo VARCHAR(50) NOT NULL, orgao_julgador VARCHAR(255) NOT NULL, sigla_tribunal VARCHAR(20) NOT NULL, classe_processual VARCHAR(255) NOT NULL, assunto_processual VARCHAR(255) NOT NULL, partes JSON DEFAULT NULL, movimentacoes JSON DEFAULT NULL, data_distribuicao DATE DEFAULT NULL, data_baixa DATE DEFAULT NULL, situacao_processo VARCHAR(30) NOT NULL, instancia VARCHAR(20) NOT NULL, processo_pai VARCHAR(50) DEFAULT NULL, data_atualizacao TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1FDCC2B251C716A9 ON processo (numero_processo)');
        $this->addSql('CREATE INDEX IDX_1FDCC2B29C7FDD7C ON processo (contrato_id)');
        $this->addSql('ALTER TABLE processo ADD CONSTRAINT FK_1FDCC2B29C7FDD7C FOREIGN KEY (contrato_id) REFERENCES contrato (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE processo');
    }
}
