<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260331163739 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE escala_trabalho (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entrada1 VARCHAR(5) DEFAULT NULL, saida1 VARCHAR(5) DEFAULT NULL, entrada2 VARCHAR(5) DEFAULT NULL, saida2 VARCHAR(5) DEFAULT NULL, carga_horaria_diaria INT NOT NULL, dias_semana JSON NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_3863840EA76ED395 ON escala_trabalho (user_id)');
        $this->addSql('CREATE TABLE feriado (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, data DATE NOT NULL, recorrente BOOLEAN NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_7D8640139033212A ON feriado (tenant_id)');
        $this->addSql('CREATE TABLE justificativa_ponto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data DATE NOT NULL, descricao TEXT NOT NULL, anexo_path VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, data_analise TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observacao_analise TEXT DEFAULT NULL, user_id INT NOT NULL, analisado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_211D30B6A76ED395 ON justificativa_ponto (user_id)');
        $this->addSql('CREATE INDEX IDX_211D30B628F56883 ON justificativa_ponto (analisado_por_id)');
        $this->addSql('CREATE TABLE registro_ponto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data_hora TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, latitude NUMERIC(10, 8) NOT NULL, longitude NUMERIC(11, 8) NOT NULL, precisao_gps NUMERIC(10, 2) NOT NULL, ssid VARCHAR(255) DEFAULT NULL, tipo VARCHAR(20) NOT NULL, observacao TEXT DEFAULT NULL, user_id INT NOT NULL, sede_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2ED7D752A76ED395 ON registro_ponto (user_id)');
        $this->addSql('CREATE INDEX IDX_2ED7D752E19F41BF ON registro_ponto (sede_id)');
        $this->addSql('CREATE TABLE sede (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, latitude NUMERIC(10, 8) NOT NULL, longitude NUMERIC(11, 8) NOT NULL, raio_permitido INT NOT NULL, timezone VARCHAR(50) NOT NULL, ssids_autorizados JSON DEFAULT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2A9BE2D19033212A ON sede (tenant_id)');
        $this->addSql('ALTER TABLE escala_trabalho ADD CONSTRAINT FK_3863840EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE feriado ADD CONSTRAINT FK_7D8640139033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE justificativa_ponto ADD CONSTRAINT FK_211D30B6A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE justificativa_ponto ADD CONSTRAINT FK_211D30B628F56883 FOREIGN KEY (analisado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registro_ponto ADD CONSTRAINT FK_2ED7D752A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE registro_ponto ADD CONSTRAINT FK_2ED7D752E19F41BF FOREIGN KEY (sede_id) REFERENCES sede (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sede ADD CONSTRAINT FK_2A9BE2D19033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('DROP INDEX uniq_access_request_pending');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE escala_trabalho DROP CONSTRAINT FK_3863840EA76ED395');
        $this->addSql('ALTER TABLE feriado DROP CONSTRAINT FK_7D8640139033212A');
        $this->addSql('ALTER TABLE justificativa_ponto DROP CONSTRAINT FK_211D30B6A76ED395');
        $this->addSql('ALTER TABLE justificativa_ponto DROP CONSTRAINT FK_211D30B628F56883');
        $this->addSql('ALTER TABLE registro_ponto DROP CONSTRAINT FK_2ED7D752A76ED395');
        $this->addSql('ALTER TABLE registro_ponto DROP CONSTRAINT FK_2ED7D752E19F41BF');
        $this->addSql('ALTER TABLE sede DROP CONSTRAINT FK_2A9BE2D19033212A');
        $this->addSql('DROP TABLE escala_trabalho');
        $this->addSql('DROP TABLE feriado');
        $this->addSql('DROP TABLE justificativa_ponto');
        $this->addSql('DROP TABLE registro_ponto');
        $this->addSql('DROP TABLE sede');
        $this->addSql('CREATE UNIQUE INDEX uniq_access_request_pending ON access_request (user_id, resource_type, resource_id, action) WHERE ((status)::text = \'pending\'::text)');
    }
}
