<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260506134513 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE kanban_anexo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome_original VARCHAR(500) NOT NULL, caminho VARCHAR(500) NOT NULL, tamanho INT NOT NULL, mime_type VARCHAR(255) NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, card_id INT NOT NULL, criado_por_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3FB8AFFE4ACC9A20 ON kanban_anexo (card_id)');
        $this->addSql('CREATE INDEX IDX_3FB8AFFEF42F4A03 ON kanban_anexo (criado_por_id)');
        $this->addSql('CREATE TABLE kanban_board (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, descricao TEXT DEFAULT NULL, cor VARCHAR(7) DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, criado_por_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA902B959033212A ON kanban_board (tenant_id)');
        $this->addSql('CREATE INDEX IDX_AA902B95F42F4A03 ON kanban_board (criado_por_id)');
        $this->addSql('CREATE TABLE kanban_board_participante (kanban_board_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (kanban_board_id, user_id))');
        $this->addSql('CREATE INDEX IDX_D86A830E1BE6D1AC ON kanban_board_participante (kanban_board_id)');
        $this->addSql('CREATE INDEX IDX_D86A830EA76ED395 ON kanban_board_participante (user_id)');
        $this->addSql('CREATE TABLE kanban_card (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(500) NOT NULL, descricao TEXT DEFAULT NULL, posicao INT NOT NULL, data_vencimento TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, coluna_id INT NOT NULL, board_id INT NOT NULL, criado_por_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B2140480A14DE453 ON kanban_card (coluna_id)');
        $this->addSql('CREATE INDEX IDX_B2140480E7EC5785 ON kanban_card (board_id)');
        $this->addSql('CREATE INDEX IDX_B2140480F42F4A03 ON kanban_card (criado_por_id)');
        $this->addSql('CREATE TABLE kanban_card_responsavel (kanban_card_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (kanban_card_id, user_id))');
        $this->addSql('CREATE INDEX IDX_27176253F9C2CF7B ON kanban_card_responsavel (kanban_card_id)');
        $this->addSql('CREATE INDEX IDX_27176253A76ED395 ON kanban_card_responsavel (user_id)');
        $this->addSql('CREATE TABLE kanban_card_marcador (kanban_card_id INT NOT NULL, kanban_marcador_id INT NOT NULL, PRIMARY KEY (kanban_card_id, kanban_marcador_id))');
        $this->addSql('CREATE INDEX IDX_3135991F9C2CF7B ON kanban_card_marcador (kanban_card_id)');
        $this->addSql('CREATE INDEX IDX_31359919B37C62 ON kanban_card_marcador (kanban_marcador_id)');
        $this->addSql('CREATE TABLE kanban_checklist (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, posicao INT NOT NULL, card_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_1E27FFC54ACC9A20 ON kanban_checklist (card_id)');
        $this->addSql('CREATE TABLE kanban_checklist_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, texto VARCHAR(500) NOT NULL, concluido BOOLEAN NOT NULL, posicao INT NOT NULL, checklist_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_548D5BE5B16D08A7 ON kanban_checklist_item (checklist_id)');
        $this->addSql('CREATE TABLE kanban_coluna (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(100) NOT NULL, tipo VARCHAR(20) NOT NULL, posicao INT NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AEEEBCD4E7EC5785 ON kanban_coluna (board_id)');
        $this->addSql('CREATE TABLE kanban_comentario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conteudo TEXT NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, card_id INT NOT NULL, criado_por_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B0CA2F64ACC9A20 ON kanban_comentario (card_id)');
        $this->addSql('CREATE INDEX IDX_B0CA2F6F42F4A03 ON kanban_comentario (criado_por_id)');
        $this->addSql('CREATE TABLE kanban_marcador (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(100) NOT NULL, cor VARCHAR(7) NOT NULL, board_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F7559ECEE7EC5785 ON kanban_marcador (board_id)');
        $this->addSql('ALTER TABLE kanban_anexo ADD CONSTRAINT FK_3FB8AFFE4ACC9A20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_anexo ADD CONSTRAINT FK_3FB8AFFEF42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_board ADD CONSTRAINT FK_AA902B959033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_board ADD CONSTRAINT FK_AA902B95F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_board_participante ADD CONSTRAINT FK_D86A830E1BE6D1AC FOREIGN KEY (kanban_board_id) REFERENCES kanban_board (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kanban_board_participante ADD CONSTRAINT FK_D86A830EA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kanban_card ADD CONSTRAINT FK_B2140480A14DE453 FOREIGN KEY (coluna_id) REFERENCES kanban_coluna (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card ADD CONSTRAINT FK_B2140480E7EC5785 FOREIGN KEY (board_id) REFERENCES kanban_board (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card ADD CONSTRAINT FK_B2140480F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_card_responsavel ADD CONSTRAINT FK_27176253F9C2CF7B FOREIGN KEY (kanban_card_id) REFERENCES kanban_card (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kanban_card_responsavel ADD CONSTRAINT FK_27176253A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kanban_card_marcador ADD CONSTRAINT FK_3135991F9C2CF7B FOREIGN KEY (kanban_card_id) REFERENCES kanban_card (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kanban_card_marcador ADD CONSTRAINT FK_31359919B37C62 FOREIGN KEY (kanban_marcador_id) REFERENCES kanban_marcador (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE kanban_checklist ADD CONSTRAINT FK_1E27FFC54ACC9A20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_checklist_item ADD CONSTRAINT FK_548D5BE5B16D08A7 FOREIGN KEY (checklist_id) REFERENCES kanban_checklist (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_coluna ADD CONSTRAINT FK_AEEEBCD4E7EC5785 FOREIGN KEY (board_id) REFERENCES kanban_board (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_comentario ADD CONSTRAINT FK_B0CA2F64ACC9A20 FOREIGN KEY (card_id) REFERENCES kanban_card (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_comentario ADD CONSTRAINT FK_B0CA2F6F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE kanban_marcador ADD CONSTRAINT FK_F7559ECEE7EC5785 FOREIGN KEY (board_id) REFERENCES kanban_board (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE kanban_anexo DROP CONSTRAINT FK_3FB8AFFE4ACC9A20');
        $this->addSql('ALTER TABLE kanban_anexo DROP CONSTRAINT FK_3FB8AFFEF42F4A03');
        $this->addSql('ALTER TABLE kanban_board DROP CONSTRAINT FK_AA902B959033212A');
        $this->addSql('ALTER TABLE kanban_board DROP CONSTRAINT FK_AA902B95F42F4A03');
        $this->addSql('ALTER TABLE kanban_board_participante DROP CONSTRAINT FK_D86A830E1BE6D1AC');
        $this->addSql('ALTER TABLE kanban_board_participante DROP CONSTRAINT FK_D86A830EA76ED395');
        $this->addSql('ALTER TABLE kanban_card DROP CONSTRAINT FK_B2140480A14DE453');
        $this->addSql('ALTER TABLE kanban_card DROP CONSTRAINT FK_B2140480E7EC5785');
        $this->addSql('ALTER TABLE kanban_card DROP CONSTRAINT FK_B2140480F42F4A03');
        $this->addSql('ALTER TABLE kanban_card_responsavel DROP CONSTRAINT FK_27176253F9C2CF7B');
        $this->addSql('ALTER TABLE kanban_card_responsavel DROP CONSTRAINT FK_27176253A76ED395');
        $this->addSql('ALTER TABLE kanban_card_marcador DROP CONSTRAINT FK_3135991F9C2CF7B');
        $this->addSql('ALTER TABLE kanban_card_marcador DROP CONSTRAINT FK_31359919B37C62');
        $this->addSql('ALTER TABLE kanban_checklist DROP CONSTRAINT FK_1E27FFC54ACC9A20');
        $this->addSql('ALTER TABLE kanban_checklist_item DROP CONSTRAINT FK_548D5BE5B16D08A7');
        $this->addSql('ALTER TABLE kanban_coluna DROP CONSTRAINT FK_AEEEBCD4E7EC5785');
        $this->addSql('ALTER TABLE kanban_comentario DROP CONSTRAINT FK_B0CA2F64ACC9A20');
        $this->addSql('ALTER TABLE kanban_comentario DROP CONSTRAINT FK_B0CA2F6F42F4A03');
        $this->addSql('ALTER TABLE kanban_marcador DROP CONSTRAINT FK_F7559ECEE7EC5785');
        $this->addSql('DROP TABLE kanban_anexo');
        $this->addSql('DROP TABLE kanban_board');
        $this->addSql('DROP TABLE kanban_board_participante');
        $this->addSql('DROP TABLE kanban_card');
        $this->addSql('DROP TABLE kanban_card_responsavel');
        $this->addSql('DROP TABLE kanban_card_marcador');
        $this->addSql('DROP TABLE kanban_checklist');
        $this->addSql('DROP TABLE kanban_checklist_item');
        $this->addSql('DROP TABLE kanban_coluna');
        $this->addSql('DROP TABLE kanban_comentario');
        $this->addSql('DROP TABLE kanban_marcador');
    }
}
