<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260325162504 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // 1. Remove FK from processo.contrato_id first (depends on contrato table)
        $this->addSql('ALTER TABLE processo DROP CONSTRAINT fk_16e5b82d70ae7bf1');
        $this->addSql('DROP INDEX idx_16e5b82d70ae7bf1');
        $this->addSql('ALTER TABLE processo DROP contrato_id');
        // 2. Remove junction table cliente_contrato
        $this->addSql('ALTER TABLE cliente_contrato DROP CONSTRAINT fk_88f9f1ef3b4da9c0');
        $this->addSql('ALTER TABLE cliente_contrato DROP CONSTRAINT fk_88f9f1ef19eb6921');
        $this->addSql('DROP TABLE cliente_contrato');
        // 3. Remove contrato table (no more dependents)
        $this->addSql('ALTER TABLE contrato DROP CONSTRAINT fk_3d3ae85853c59d72');
        $this->addSql('DROP TABLE contrato');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cliente_contrato (cliente_id INT NOT NULL, contrato_id INT NOT NULL, PRIMARY KEY (cliente_id, contrato_id))');
        $this->addSql('CREATE INDEX idx_dc58e2bd70ae7bf1 ON cliente_contrato (contrato_id)');
        $this->addSql('CREATE INDEX IDX_DC58E2BDDE734E51 ON cliente_contrato (cliente_id)');
        $this->addSql('CREATE TABLE contrato (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, criado_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modificado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_inicio DATE DEFAULT NULL, valor_total NUMERIC(12, 2) DEFAULT NULL, responsavel_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, descricao TEXT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_66696523bb9af004 ON contrato (responsavel_id)');
        $this->addSql('ALTER TABLE cliente_contrato ADD CONSTRAINT fk_88f9f1ef3b4da9c0 FOREIGN KEY (contrato_id) REFERENCES contrato (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cliente_contrato ADD CONSTRAINT fk_88f9f1ef19eb6921 FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE contrato ADD CONSTRAINT fk_3d3ae85853c59d72 FOREIGN KEY (responsavel_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE processo ADD contrato_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE processo ADD CONSTRAINT fk_16e5b82d70ae7bf1 FOREIGN KEY (contrato_id) REFERENCES contrato (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_16e5b82d70ae7bf1 ON processo (contrato_id)');
    }
}
