<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Favoritos de pasta: a pasta que o usuário fixou pelo menu ⋮ (desenho 1.2.3, `prefPasta('fav')`)
 * e que sobe para o topo da listagem do Expediente — só para ele.
 *
 * Escrita à mão (não por `make:migration`), com os nomes que o Doctrine derivaria do mapeamento
 * de `App\Pasta\Entity\PastaFavorita`: índices e unique declarados lá; FKs pelo hash padrão do
 * DBAL (`FK_` + crc32 da tabela e da coluna), para o `doctrine:schema:validate` não propor nada.
 *
 * Anatomia das FKs:
 *   - `pasta_id` CASCADE: a preferência é sobre a pasta; some com ela;
 *   - `user_id` CASCADE: preferência pessoal; some com o usuário;
 *   - `tenant_id` sem ação (padrão): a purga do escritório apaga explicitamente
 *     (`PurgarEscritorioUseCase::ORDEM_DELECAO`).
 *
 * Os índices implícitos de FK não são criados: `tenant_id` é coberto por
 * `idx_pasta_favorita_tenant_user`, `user_id` pelo unique `(user_id, pasta_id)` e `pasta_id` por
 * `idx_pasta_favorita_pasta`.
 */
final class Version20261006121500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria pasta_favorita: pastas fixadas nos favoritos por usuário';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pasta_favorita (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, user_id INT NOT NULL, pasta_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_pasta_favorita_tenant_user ON pasta_favorita (tenant_id, user_id)');
        $this->addSql('CREATE INDEX idx_pasta_favorita_pasta ON pasta_favorita (pasta_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pasta_favorita_user_pasta ON pasta_favorita (user_id, pasta_id)');
        $this->addSql('ALTER TABLE pasta_favorita ADD CONSTRAINT FK_6CDACF6C9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_favorita ADD CONSTRAINT FK_6CDACF6CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_favorita ADD CONSTRAINT FK_6CDACF6C7FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pasta_favorita DROP CONSTRAINT FK_6CDACF6C9033212A');
        $this->addSql('ALTER TABLE pasta_favorita DROP CONSTRAINT FK_6CDACF6CA76ED395');
        $this->addSql('ALTER TABLE pasta_favorita DROP CONSTRAINT FK_6CDACF6C7FCDBC8C');
        $this->addSql('DROP TABLE pasta_favorita');
    }
}
