<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260411200925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pasta_organizadora (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(100) NOT NULL, ordem INT NOT NULL, criado_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pai_id INT DEFAULT NULL, tenant_id INT NOT NULL, criado_por_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9EEA0CC4C19C5634 ON pasta_organizadora (pai_id)');
        $this->addSql('CREATE INDEX IDX_9EEA0CC49033212A ON pasta_organizadora (tenant_id)');
        $this->addSql('CREATE INDEX IDX_9EEA0CC4F42F4A03 ON pasta_organizadora (criado_por_id)');
        $this->addSql('ALTER TABLE pasta_organizadora ADD CONSTRAINT FK_9EEA0CC4C19C5634 FOREIGN KEY (pai_id) REFERENCES pasta_organizadora (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_organizadora ADD CONSTRAINT FK_9EEA0CC49033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_organizadora ADD CONSTRAINT FK_9EEA0CC4F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pasta_organizadora DROP CONSTRAINT FK_9EEA0CC4C19C5634');
        $this->addSql('ALTER TABLE pasta_organizadora DROP CONSTRAINT FK_9EEA0CC49033212A');
        $this->addSql('ALTER TABLE pasta_organizadora DROP CONSTRAINT FK_9EEA0CC4F42F4A03');
        $this->addSql('DROP TABLE pasta_organizadora');
    }
}
