<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Cobrança — qualificação da Pessoa cobrada + listas de endereço/telefone/e-mail (spec de
 * qualificação §3/§4/§5). ADITIVA: 5 colunas novas em cobranca_pessoa (todas NULL) + 3 tabelas
 * novas de lista (histórico por adição, um "atual" por lista) + backfill de email/telefone
 * legados para o item atual de suas respectivas listas. As colunas email/telefone de
 * cobranca_pessoa PERMANECEM como sombra por 1 release (SPEC §5.4/§6).
 */
final class Version20260722023029 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cobranca: qualificacao da pessoa (5 colunas) + listas endereco/telefone/email + backfill';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql(<<<'SQL'
            CREATE TABLE cobranca_pessoa_email (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              email VARCHAR(255) NOT NULL,
              atual BOOLEAN NOT NULL,
              criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              tenant_id INT NOT NULL,
              pessoa_id INT NOT NULL,
              criado_por_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_713C36939033212A ON cobranca_pessoa_email (tenant_id)');
        $this->addSql('CREATE INDEX IDX_713C3693DF6FA0A5 ON cobranca_pessoa_email (pessoa_id)');
        $this->addSql('CREATE INDEX IDX_713C3693F42F4A03 ON cobranca_pessoa_email (criado_por_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE cobranca_pessoa_endereco (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              logradouro VARCHAR(255) NOT NULL,
              numero VARCHAR(20) NOT NULL,
              complemento VARCHAR(120) DEFAULT NULL,
              bairro VARCHAR(120) NOT NULL,
              cidade VARCHAR(120) NOT NULL,
              uf VARCHAR(2) NOT NULL,
              cep VARCHAR(9) NOT NULL,
              atual BOOLEAN NOT NULL,
              criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              tenant_id INT NOT NULL,
              pessoa_id INT NOT NULL,
              criado_por_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_6FB539DD9033212A ON cobranca_pessoa_endereco (tenant_id)');
        $this->addSql('CREATE INDEX IDX_6FB539DDDF6FA0A5 ON cobranca_pessoa_endereco (pessoa_id)');
        $this->addSql('CREATE INDEX IDX_6FB539DDF42F4A03 ON cobranca_pessoa_endereco (criado_por_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE cobranca_pessoa_telefone (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              numero VARCHAR(20) NOT NULL,
              atual BOOLEAN NOT NULL,
              criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              tenant_id INT NOT NULL,
              pessoa_id INT NOT NULL,
              criado_por_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_B6670CB29033212A ON cobranca_pessoa_telefone (tenant_id)');
        $this->addSql('CREATE INDEX IDX_B6670CB2DF6FA0A5 ON cobranca_pessoa_telefone (pessoa_id)');
        $this->addSql('CREATE INDEX IDX_B6670CB2F42F4A03 ON cobranca_pessoa_telefone (criado_por_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_pessoa_email
            ADD
              CONSTRAINT FK_713C36939033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_pessoa_email
            ADD
              CONSTRAINT FK_713C3693DF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES cobranca_pessoa (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_pessoa_email
            ADD
              CONSTRAINT FK_713C3693F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_pessoa_endereco
            ADD
              CONSTRAINT FK_6FB539DD9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_pessoa_endereco
            ADD
              CONSTRAINT FK_6FB539DDDF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES cobranca_pessoa (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_pessoa_endereco
            ADD
              CONSTRAINT FK_6FB539DDF42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_pessoa_telefone
            ADD
              CONSTRAINT FK_B6670CB29033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_pessoa_telefone
            ADD
              CONSTRAINT FK_B6670CB2DF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES cobranca_pessoa (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_pessoa_telefone
            ADD
              CONSTRAINT FK_B6670CB2F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql('ALTER TABLE cobranca_pessoa ADD data_nascimento DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE cobranca_pessoa ADD estado_civil VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE cobranca_pessoa ADD profissao VARCHAR(120) DEFAULT NULL');
        $this->addSql('ALTER TABLE cobranca_pessoa ADD rg VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE cobranca_pessoa ADD orgao_emissor_rg VARCHAR(20) DEFAULT NULL');

        // Backfill (SPEC §5.3): email/telefone legados viram o item ATUAL da respectiva lista.
        // As colunas email/telefone de cobranca_pessoa permanecem intactas (sombra, SPEC §5.4).
        $this->addSql(<<<'SQL'
            INSERT INTO cobranca_pessoa_email (email, atual, criado_em, tenant_id, pessoa_id)
            SELECT email, true, now(), tenant_id, id
            FROM cobranca_pessoa
            WHERE email IS NOT NULL AND trim(email) <> ''
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO cobranca_pessoa_telefone (numero, atual, criado_em, tenant_id, pessoa_id)
            SELECT telefone, true, now(), tenant_id, id
            FROM cobranca_pessoa
            WHERE telefone IS NOT NULL AND trim(telefone) <> ''
        SQL);
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cobranca_pessoa_email DROP CONSTRAINT FK_713C36939033212A');
        $this->addSql('ALTER TABLE cobranca_pessoa_email DROP CONSTRAINT FK_713C3693DF6FA0A5');
        $this->addSql('ALTER TABLE cobranca_pessoa_email DROP CONSTRAINT FK_713C3693F42F4A03');
        $this->addSql('ALTER TABLE cobranca_pessoa_endereco DROP CONSTRAINT FK_6FB539DD9033212A');
        $this->addSql('ALTER TABLE cobranca_pessoa_endereco DROP CONSTRAINT FK_6FB539DDDF6FA0A5');
        $this->addSql('ALTER TABLE cobranca_pessoa_endereco DROP CONSTRAINT FK_6FB539DDF42F4A03');
        $this->addSql('ALTER TABLE cobranca_pessoa_telefone DROP CONSTRAINT FK_B6670CB29033212A');
        $this->addSql('ALTER TABLE cobranca_pessoa_telefone DROP CONSTRAINT FK_B6670CB2DF6FA0A5');
        $this->addSql('ALTER TABLE cobranca_pessoa_telefone DROP CONSTRAINT FK_B6670CB2F42F4A03');
        // O backfill dos INSERTs acima é descartado junto com as tabelas — nada a reverter à parte.
        $this->addSql('DROP TABLE cobranca_pessoa_email');
        $this->addSql('DROP TABLE cobranca_pessoa_endereco');
        $this->addSql('DROP TABLE cobranca_pessoa_telefone');
        $this->addSql('ALTER TABLE cobranca_pessoa DROP data_nascimento');
        $this->addSql('ALTER TABLE cobranca_pessoa DROP estado_civil');
        $this->addSql('ALTER TABLE cobranca_pessoa DROP profissao');
        $this->addSql('ALTER TABLE cobranca_pessoa DROP rg');
        $this->addSql('ALTER TABLE cobranca_pessoa DROP orgao_emissor_rg');
    }
}
