<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Cobrança — documentos da Carteira (Ajuste #5) e do Acordo (Ajuste #4). ADITIVA: cria
 * `cobranca_carteira_documento` e `cobranca_acordo_documento` (FK onDelete CASCADE ao dono,
 * `tenant_id` NOT NULL, índices por dono e por tenant). Sem backfill — não havia documentos
 * nesses níveis antes desta migração. Os arquivos físicos mora no MESMO diretório flat dos
 * documentos de Caso (`cobrancas/<tenantId>/<hash>`, decisão deliberada) — nenhuma mudança de
 * infraestrutura de disco aqui.
 */
final class Version20260722040000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cobranca: documentos da carteira (Ajuste #5) e do acordo (Ajuste #4)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE cobranca_carteira_documento (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              titulo VARCHAR(255) NOT NULL,
              categoria VARCHAR(255) NOT NULL,
              observacao TEXT DEFAULT NULL,
              caminho_arquivo VARCHAR(255) NOT NULL,
              nome_original VARCHAR(255) NOT NULL,
              mime_type VARCHAR(100) NOT NULL,
              tamanho_bytes INT NOT NULL,
              uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              carteira_id INT NOT NULL,
              tenant_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_cobranca_carteira_documento_carteira ON cobranca_carteira_documento (carteira_id)');
        $this->addSql('CREATE INDEX idx_cobranca_carteira_documento_tenant ON cobranca_carteira_documento (tenant_id)');
        $this->addSql(<<<'SQL'
            CREATE TABLE cobranca_acordo_documento (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              titulo VARCHAR(255) NOT NULL,
              categoria VARCHAR(255) NOT NULL,
              observacao TEXT DEFAULT NULL,
              caminho_arquivo VARCHAR(255) NOT NULL,
              nome_original VARCHAR(255) NOT NULL,
              mime_type VARCHAR(100) NOT NULL,
              tamanho_bytes INT NOT NULL,
              uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              acordo_id INT NOT NULL,
              tenant_id INT NOT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_cobranca_acordo_documento_acordo ON cobranca_acordo_documento (acordo_id)');
        $this->addSql('CREATE INDEX idx_cobranca_acordo_documento_tenant ON cobranca_acordo_documento (tenant_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_carteira_documento
            ADD
              CONSTRAINT FK_23BC35C05265899 FOREIGN KEY (carteira_id) REFERENCES cobranca_carteira (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_carteira_documento
            ADD
              CONSTRAINT FK_23BC35C09033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_acordo_documento
            ADD
              CONSTRAINT FK_717C78775E969C2D FOREIGN KEY (acordo_id) REFERENCES cobranca_acordo (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              cobranca_acordo_documento
            ADD
              CONSTRAINT FK_717C78779033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cobranca_carteira_documento DROP CONSTRAINT FK_23BC35C05265899');
        $this->addSql('ALTER TABLE cobranca_carteira_documento DROP CONSTRAINT FK_23BC35C09033212A');
        $this->addSql('ALTER TABLE cobranca_acordo_documento DROP CONSTRAINT FK_717C78775E969C2D');
        $this->addSql('ALTER TABLE cobranca_acordo_documento DROP CONSTRAINT FK_717C78779033212A');
        $this->addSql('DROP TABLE cobranca_carteira_documento');
        $this->addSql('DROP TABLE cobranca_acordo_documento');
    }
}
