<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709123952 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cobranças Etapa 2 — núcleo do caso: tabelas cobranca_caso, cobranca_obrigacao '
            . '(valores em centavos INT) e cobranca_evento_historico (linha do tempo operacional), '
            . 'todas escopadas por tenant.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cobranca_caso (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, forma_honorarios VARCHAR(255) NOT NULL, percentual_honorarios NUMERIC(5, 2) DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, objeto_id INT NOT NULL, pessoa_cobrada_atual_id INT NOT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E8DA23C29033212A ON cobranca_caso (tenant_id)');
        $this->addSql('CREATE INDEX IDX_E8DA23C276F5CD27 ON cobranca_caso (objeto_id)');
        $this->addSql('CREATE INDEX IDX_E8DA23C2803979D0 ON cobranca_caso (pessoa_cobrada_atual_id)');
        $this->addSql('CREATE INDEX IDX_E8DA23C2F42F4A03 ON cobranca_caso (criado_por_id)');
        $this->addSql('CREATE INDEX idx_cobranca_caso_tenant_objeto ON cobranca_caso (tenant_id, objeto_id)');
        $this->addSql('CREATE TABLE cobranca_evento_historico (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo VARCHAR(255) NOT NULL, ocorrido_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, descricao TEXT NOT NULL, dados JSON DEFAULT NULL, tenant_id INT NOT NULL, caso_id INT NOT NULL, usuario_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_192126DF9033212A ON cobranca_evento_historico (tenant_id)');
        $this->addSql('CREATE INDEX IDX_192126DFA0AD3491 ON cobranca_evento_historico (caso_id)');
        $this->addSql('CREATE INDEX IDX_192126DFDB38439E ON cobranca_evento_historico (usuario_id)');
        $this->addSql('CREATE INDEX idx_cobranca_evento_tenant_caso ON cobranca_evento_historico (tenant_id, caso_id)');
        $this->addSql('CREATE TABLE cobranca_obrigacao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descricao VARCHAR(255) NOT NULL, valor_original INT NOT NULL, vencimento_original DATE NOT NULL, encargos_reconhecidos INT DEFAULT 0 NOT NULL, referencia_externa VARCHAR(255) DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, caso_id INT NOT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AAAEF1479033212A ON cobranca_obrigacao (tenant_id)');
        $this->addSql('CREATE INDEX IDX_AAAEF147A0AD3491 ON cobranca_obrigacao (caso_id)');
        $this->addSql('CREATE INDEX IDX_AAAEF147F42F4A03 ON cobranca_obrigacao (criado_por_id)');
        $this->addSql('CREATE INDEX idx_cobranca_obrigacao_tenant_caso ON cobranca_obrigacao (tenant_id, caso_id)');
        $this->addSql('ALTER TABLE cobranca_caso ADD CONSTRAINT FK_E8DA23C29033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_caso ADD CONSTRAINT FK_E8DA23C276F5CD27 FOREIGN KEY (objeto_id) REFERENCES cobranca_objeto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_caso ADD CONSTRAINT FK_E8DA23C2803979D0 FOREIGN KEY (pessoa_cobrada_atual_id) REFERENCES cobranca_pessoa (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_caso ADD CONSTRAINT FK_E8DA23C2F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_evento_historico ADD CONSTRAINT FK_192126DF9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_evento_historico ADD CONSTRAINT FK_192126DFA0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_evento_historico ADD CONSTRAINT FK_192126DFDB38439E FOREIGN KEY (usuario_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_obrigacao ADD CONSTRAINT FK_AAAEF1479033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_obrigacao ADD CONSTRAINT FK_AAAEF147A0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_obrigacao ADD CONSTRAINT FK_AAAEF147F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cobranca_caso DROP CONSTRAINT FK_E8DA23C29033212A');
        $this->addSql('ALTER TABLE cobranca_caso DROP CONSTRAINT FK_E8DA23C276F5CD27');
        $this->addSql('ALTER TABLE cobranca_caso DROP CONSTRAINT FK_E8DA23C2803979D0');
        $this->addSql('ALTER TABLE cobranca_caso DROP CONSTRAINT FK_E8DA23C2F42F4A03');
        $this->addSql('ALTER TABLE cobranca_evento_historico DROP CONSTRAINT FK_192126DF9033212A');
        $this->addSql('ALTER TABLE cobranca_evento_historico DROP CONSTRAINT FK_192126DFA0AD3491');
        $this->addSql('ALTER TABLE cobranca_evento_historico DROP CONSTRAINT FK_192126DFDB38439E');
        $this->addSql('ALTER TABLE cobranca_obrigacao DROP CONSTRAINT FK_AAAEF1479033212A');
        $this->addSql('ALTER TABLE cobranca_obrigacao DROP CONSTRAINT FK_AAAEF147A0AD3491');
        $this->addSql('ALTER TABLE cobranca_obrigacao DROP CONSTRAINT FK_AAAEF147F42F4A03');
        $this->addSql('DROP TABLE cobranca_caso');
        $this->addSql('DROP TABLE cobranca_evento_historico');
        $this->addSql('DROP TABLE cobranca_obrigacao');
    }
}
