<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222140000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE contrato (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome_arquivo VARCHAR(255) NOT NULL, caminho_arquivo VARCHAR(255) NOT NULL, status VARCHAR(20) NOT NULL, criado_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, modificado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE cliente_contrato (cliente_id INT NOT NULL, contrato_id INT NOT NULL, PRIMARY KEY(cliente_id, contrato_id))');
        $this->addSql('CREATE INDEX IDX_88F9F1EF3B4DA9C0 ON cliente_contrato (contrato_id)');
        $this->addSql('ALTER TABLE cliente_contrato ADD CONSTRAINT FK_88F9F1EF19EB6921 FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cliente_contrato ADD CONSTRAINT FK_88F9F1EF3B4DA9C0 FOREIGN KEY (contrato_id) REFERENCES contrato (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cliente DROP COLUMN IF EXISTS contrato_arquivo');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cliente ADD COLUMN contrato_arquivo VARCHAR(255) DEFAULT NULL');
        $this->addSql('DROP TABLE cliente_contrato');
        $this->addSql('DROP TABLE contrato');
    }
}
