<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260428155807 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pasta_secao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, ordem INT DEFAULT 0 NOT NULL, criada_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pasta_id INT NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_pasta_secao_pasta ON pasta_secao (pasta_id)');
        $this->addSql('CREATE INDEX idx_pasta_secao_tenant ON pasta_secao (tenant_id)');
        $this->addSql('ALTER TABLE pasta_secao ADD CONSTRAINT FK_C35DDF207FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_secao ADD CONSTRAINT FK_C35DDF209033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_documento ADD secao_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pasta_documento ADD CONSTRAINT FK_69D2B3814E04F226 FOREIGN KEY (secao_id) REFERENCES pasta_secao (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_69D2B3814E04F226 ON pasta_documento (secao_id)');
        $this->addSql('ALTER INDEX idx_tenant_criado_por RENAME TO IDX_4E59C462F42F4A03');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pasta_secao DROP CONSTRAINT FK_C35DDF207FCDBC8C');
        $this->addSql('ALTER TABLE pasta_secao DROP CONSTRAINT FK_C35DDF209033212A');
        $this->addSql('DROP TABLE pasta_secao');
        $this->addSql('ALTER TABLE pasta_documento DROP CONSTRAINT FK_69D2B3814E04F226');
        $this->addSql('DROP INDEX IDX_69D2B3814E04F226');
        $this->addSql('ALTER TABLE pasta_documento DROP secao_id');
        $this->addSql('ALTER INDEX idx_4e59c462f42f4a03 RENAME TO idx_tenant_criado_por');
    }
}
