<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-cadastro público (Fase 3): tabela cadastro_pendente.
 *
 * Guarda o cadastro (conta + primeiro escritório) iniciado numa página pública
 * até a confirmação por e-mail, quando vira User + Tenant + vínculo dono.
 */
final class Version20260701130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria cadastro_pendente para auto-cadastro público com confirmação por e-mail';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cadastro_pendente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, confirmed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, email VARCHAR(180) NOT NULL, token VARCHAR(64) NOT NULL, nome_completo VARCHAR(255) NOT NULL, nome_escritorio VARCHAR(255) NOT NULL, oab_numero VARCHAR(20) NOT NULL, oab_uf VARCHAR(2) NOT NULL, senha_hash VARCHAR(255) NOT NULL, ip VARCHAR(45) NOT NULL, expires_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, user_agent VARCHAR(255) DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cadastro_pendente_email ON cadastro_pendente (email)');
        $this->addSql('CREATE UNIQUE INDEX uq_cadastro_pendente_token ON cadastro_pendente (token)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE cadastro_pendente');
    }
}
