<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709191327 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cobranças Etapa 5 — estados/judicialização/ações/revisões: cria cobranca_proxima_acao '
            . '(máx. 1 pendente por caso) e cobranca_revisao_pessoa_cobrada (pendência de revisão de '
            . 'vínculo), ambas escopadas por tenant, e ALTERA cobranca_caso adicionando pasta_judicial_id '
            . '(FK a pasta, ON DELETE SET NULL) para a judicialização unidirecional Caso → Pasta (SPEC §16/§17).';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cobranca_proxima_acao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, descricao VARCHAR(255) NOT NULL, prazo DATE DEFAULT NULL, status VARCHAR(255) NOT NULL, resultado TEXT DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, concluida_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, caso_id INT NOT NULL, responsavel_id INT DEFAULT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_859A0D0D9033212A ON cobranca_proxima_acao (tenant_id)');
        $this->addSql('CREATE INDEX IDX_859A0D0DA0AD3491 ON cobranca_proxima_acao (caso_id)');
        $this->addSql('CREATE INDEX IDX_859A0D0DBB9AF004 ON cobranca_proxima_acao (responsavel_id)');
        $this->addSql('CREATE INDEX IDX_859A0D0DF42F4A03 ON cobranca_proxima_acao (criado_por_id)');
        $this->addSql('CREATE INDEX idx_cobranca_proxima_acao_tenant_caso ON cobranca_proxima_acao (tenant_id, caso_id)');
        $this->addSql('CREATE TABLE cobranca_revisao_pessoa_cobrada (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, motivo VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, resolucao TEXT DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolvida_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, caso_id INT NOT NULL, criado_por_id INT DEFAULT NULL, resolvida_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_310C3B489033212A ON cobranca_revisao_pessoa_cobrada (tenant_id)');
        $this->addSql('CREATE INDEX IDX_310C3B48A0AD3491 ON cobranca_revisao_pessoa_cobrada (caso_id)');
        $this->addSql('CREATE INDEX IDX_310C3B48F42F4A03 ON cobranca_revisao_pessoa_cobrada (criado_por_id)');
        $this->addSql('CREATE INDEX IDX_310C3B48EC51598A ON cobranca_revisao_pessoa_cobrada (resolvida_por_id)');
        $this->addSql('CREATE INDEX idx_cobranca_revisao_tenant_caso ON cobranca_revisao_pessoa_cobrada (tenant_id, caso_id)');
        $this->addSql('ALTER TABLE cobranca_proxima_acao ADD CONSTRAINT FK_859A0D0D9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_proxima_acao ADD CONSTRAINT FK_859A0D0DA0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_proxima_acao ADD CONSTRAINT FK_859A0D0DBB9AF004 FOREIGN KEY (responsavel_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_proxima_acao ADD CONSTRAINT FK_859A0D0DF42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada ADD CONSTRAINT FK_310C3B489033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada ADD CONSTRAINT FK_310C3B48A0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada ADD CONSTRAINT FK_310C3B48F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada ADD CONSTRAINT FK_310C3B48EC51598A FOREIGN KEY (resolvida_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_caso ADD pasta_judicial_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cobranca_caso ADD CONSTRAINT FK_E8DA23C2F62D8023 FOREIGN KEY (pasta_judicial_id) REFERENCES pasta (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_E8DA23C2F62D8023 ON cobranca_caso (pasta_judicial_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cobranca_proxima_acao DROP CONSTRAINT FK_859A0D0D9033212A');
        $this->addSql('ALTER TABLE cobranca_proxima_acao DROP CONSTRAINT FK_859A0D0DA0AD3491');
        $this->addSql('ALTER TABLE cobranca_proxima_acao DROP CONSTRAINT FK_859A0D0DBB9AF004');
        $this->addSql('ALTER TABLE cobranca_proxima_acao DROP CONSTRAINT FK_859A0D0DF42F4A03');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada DROP CONSTRAINT FK_310C3B489033212A');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada DROP CONSTRAINT FK_310C3B48A0AD3491');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada DROP CONSTRAINT FK_310C3B48F42F4A03');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada DROP CONSTRAINT FK_310C3B48EC51598A');
        $this->addSql('DROP TABLE cobranca_proxima_acao');
        $this->addSql('DROP TABLE cobranca_revisao_pessoa_cobrada');
        $this->addSql('ALTER TABLE cobranca_caso DROP CONSTRAINT FK_E8DA23C2F62D8023');
        $this->addSql('DROP INDEX IDX_E8DA23C2F62D8023');
        $this->addSql('ALTER TABLE cobranca_caso DROP pasta_judicial_id');
    }
}
