<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260414181724 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pasta_mensagem (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conteudo TEXT NOT NULL, criada_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pasta_id INT NOT NULL, autor_id INT NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9D37B71C14D45BBE ON pasta_mensagem (autor_id)');
        $this->addSql('CREATE INDEX idx_pasta_mensagem_pasta_id ON pasta_mensagem (pasta_id)');
        $this->addSql('CREATE INDEX idx_pasta_mensagem_tenant ON pasta_mensagem (tenant_id)');
        $this->addSql('ALTER TABLE pasta_mensagem ADD CONSTRAINT FK_9D37B71C7FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_mensagem ADD CONSTRAINT FK_9D37B71C14D45BBE FOREIGN KEY (autor_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_mensagem ADD CONSTRAINT FK_9D37B71C9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pasta_mensagem DROP CONSTRAINT FK_9D37B71C7FCDBC8C');
        $this->addSql('ALTER TABLE pasta_mensagem DROP CONSTRAINT FK_9D37B71C14D45BBE');
        $this->addSql('ALTER TABLE pasta_mensagem DROP CONSTRAINT FK_9D37B71C9033212A');
        $this->addSql('DROP TABLE pasta_mensagem');
    }
}
