<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260423171618 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Adicionar CNPJ, endereço e tabelas cargo/lotacao ao tenant; vincular cargo e lotacao ao usuário';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cargo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(100) NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3BEE57719033212A ON cargo (tenant_id)');
        $this->addSql('CREATE TABLE lotacao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(100) NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4C6AC15F9033212A ON lotacao (tenant_id)');
        $this->addSql('ALTER TABLE cargo ADD CONSTRAINT FK_3BEE57719033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE lotacao ADD CONSTRAINT FK_4C6AC15F9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE justificativa_ponto ALTER abono_parcial DROP DEFAULT');
        $this->addSql('ALTER TABLE tenant ADD cnpj VARCHAR(14) DEFAULT NULL');
        $this->addSql('ALTER TABLE tenant ADD cep VARCHAR(9) DEFAULT NULL');
        $this->addSql('ALTER TABLE tenant ADD logradouro VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE tenant ADD numero VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE tenant ADD complemento VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE tenant ADD bairro VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE tenant ADD cidade VARCHAR(100) DEFAULT NULL');
        $this->addSql('ALTER TABLE tenant ADD estado VARCHAR(2) DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD cargo_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD lotacao_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D649813AC380 FOREIGN KEY (cargo_id) REFERENCES cargo (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE "user" ADD CONSTRAINT FK_8D93D6497E27C2B8 FOREIGN KEY (lotacao_id) REFERENCES lotacao (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_8D93D649813AC380 ON "user" (cargo_id)');
        $this->addSql('CREATE INDEX IDX_8D93D6497E27C2B8 ON "user" (lotacao_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cargo DROP CONSTRAINT FK_3BEE57719033212A');
        $this->addSql('ALTER TABLE lotacao DROP CONSTRAINT FK_4C6AC15F9033212A');
        $this->addSql('DROP TABLE cargo');
        $this->addSql('DROP TABLE lotacao');
        $this->addSql('ALTER TABLE justificativa_ponto ALTER abono_parcial SET DEFAULT false');
        $this->addSql('ALTER TABLE tenant DROP cnpj');
        $this->addSql('ALTER TABLE tenant DROP cep');
        $this->addSql('ALTER TABLE tenant DROP logradouro');
        $this->addSql('ALTER TABLE tenant DROP numero');
        $this->addSql('ALTER TABLE tenant DROP complemento');
        $this->addSql('ALTER TABLE tenant DROP bairro');
        $this->addSql('ALTER TABLE tenant DROP cidade');
        $this->addSql('ALTER TABLE tenant DROP estado');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D649813AC380');
        $this->addSql('ALTER TABLE "user" DROP CONSTRAINT FK_8D93D6497E27C2B8');
        $this->addSql('DROP INDEX IDX_8D93D649813AC380');
        $this->addSql('DROP INDEX IDX_8D93D6497E27C2B8');
        $this->addSql('ALTER TABLE "user" DROP cargo_id');
        $this->addSql('ALTER TABLE "user" DROP lotacao_id');
    }
}
