<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260706195821 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'DJEN: tabelas oab_monitorada e publicacao_djen (captação de comunicações por escritório) '
            . 'e permissão de módulo modules.djen.view no catálogo.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE oab_monitorada (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              numero VARCHAR(20) NOT NULL,
              uf VARCHAR(2) NOT NULL,
              apelido VARCHAR(255) DEFAULT NULL,
              ativo BOOLEAN NOT NULL,
              criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              tenant_id INT NOT NULL,
              criado_por_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_B3E2799A9033212A ON oab_monitorada (tenant_id)');
        $this->addSql('CREATE INDEX IDX_B3E2799AF42F4A03 ON oab_monitorada (criado_por_id)');
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_oab_monitorada_tenant_numero_uf ON oab_monitorada (tenant_id, numero, uf)
        SQL);
        $this->addSql(<<<'SQL'
            CREATE TABLE publicacao_djen (
              id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
              djen_id BIGINT NOT NULL,
              numero_comunicacao BIGINT DEFAULT NULL,
              hash VARCHAR(255) DEFAULT NULL,
              sigla_tribunal VARCHAR(20) NOT NULL,
              tipo_comunicacao VARCHAR(120) DEFAULT NULL,
              nome_orgao VARCHAR(255) DEFAULT NULL,
              numero_processo VARCHAR(50) NOT NULL,
              numero_processo_com_mascara VARCHAR(60) DEFAULT NULL,
              data_disponibilizacao DATE DEFAULT NULL,
              meio VARCHAR(1) DEFAULT NULL,
              meio_completo VARCHAR(120) DEFAULT NULL,
              texto TEXT DEFAULT NULL,
              link TEXT DEFAULT NULL,
              tipo_documento VARCHAR(255) DEFAULT NULL,
              nome_classe VARCHAR(255) DEFAULT NULL,
              codigo_classe VARCHAR(60) DEFAULT NULL,
              lida BOOLEAN NOT NULL,
              payload_djen JSONB DEFAULT NULL,
              criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
              atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
              tenant_id INT NOT NULL,
              oab_monitorada_id INT DEFAULT NULL,
              processo_id INT DEFAULT NULL,
              PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX IDX_D52530559033212A ON publicacao_djen (tenant_id)');
        $this->addSql('CREATE INDEX IDX_D5253055263CB94E ON publicacao_djen (oab_monitorada_id)');
        $this->addSql('CREATE INDEX IDX_D5253055AAA822D2 ON publicacao_djen (processo_id)');
        $this->addSql(<<<'SQL'
            CREATE INDEX idx_publicacao_djen_tenant_data ON publicacao_djen (
              tenant_id, data_disponibilizacao
            )
        SQL);
        $this->addSql('CREATE INDEX idx_publicacao_djen_tenant_numero ON publicacao_djen (tenant_id, numero_processo)');
        $this->addSql('CREATE UNIQUE INDEX uniq_publicacao_djen_tenant_djenid ON publicacao_djen (tenant_id, djen_id)');
        $this->addSql(<<<'SQL'
            ALTER TABLE
              oab_monitorada
            ADD
              CONSTRAINT FK_B3E2799A9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              oab_monitorada
            ADD
              CONSTRAINT FK_B3E2799AF42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              publicacao_djen
            ADD
              CONSTRAINT FK_D52530559033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              publicacao_djen
            ADD
              CONSTRAINT FK_D5253055263CB94E FOREIGN KEY (oab_monitorada_id) REFERENCES oab_monitorada (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE
              publicacao_djen
            ADD
              CONSTRAINT FK_D5253055AAA822D2 FOREIGN KEY (processo_id) REFERENCES processo (id) ON DELETE
            SET
              NULL NOT DEFERRABLE
        SQL);

        // Catálogo de permissão do novo módulo (idempotente — não duplica em re-execução/prod já seedada).
        // "group" é palavra reservada no Postgres, por isso vem entre aspas.
        $this->addSql(<<<'SQL'
            INSERT INTO permission (code, description, "group")
            SELECT 'modules.djen.view', 'Acesso ao módulo DJEN (publicações/intimações)', 'modules'
            WHERE NOT EXISTS (SELECT 1 FROM permission WHERE code = 'modules.djen.view')
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql(
            "DELETE FROM tenant_role_permission"
            . " WHERE permission_id = (SELECT id FROM permission WHERE code = 'modules.djen.view')"
        );
        $this->addSql("DELETE FROM permission WHERE code = 'modules.djen.view'");
        $this->addSql('ALTER TABLE oab_monitorada DROP CONSTRAINT FK_B3E2799A9033212A');
        $this->addSql('ALTER TABLE oab_monitorada DROP CONSTRAINT FK_B3E2799AF42F4A03');
        $this->addSql('ALTER TABLE publicacao_djen DROP CONSTRAINT FK_D52530559033212A');
        $this->addSql('ALTER TABLE publicacao_djen DROP CONSTRAINT FK_D5253055263CB94E');
        $this->addSql('ALTER TABLE publicacao_djen DROP CONSTRAINT FK_D5253055AAA822D2');
        $this->addSql('DROP TABLE oab_monitorada');
        $this->addSql('DROP TABLE publicacao_djen');
    }
}
