<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * BlueJus IA — fundação (spec `docs/specs/inteligencia-resumo-do-push.md`, etapa 1A).
 *
 * Duas tabelas e duas permissões:
 *   · `inteligencia_configuracao` — a IA de UM escritório (1 linha por tenant, constraint única
 *     NOMEADA; a relação é ManyToOne no mapeamento de propósito, para o índice único não nascer com
 *     nome de hash);
 *   · `inteligencia_analise` — solicitação + resultado de cada análise (status explícito, hash e
 *     resumo do contexto — NUNCA o texto enviado —, resposta bruta, soft delete);
 *   · `modules.inteligencia.view` e `admin.inteligencia.manage` no catálogo, idempotente
 *     (`WHERE NOT EXISTS`, como `Version20260711120000`), sem conceder a papéis.
 *
 * ESCRITA À MÃO (worktree sem container): os nomes de índice são os EXPLÍCITOS do mapeamento
 * (`#[ORM\Index(name:)]`/`#[ORM\UniqueConstraint(name:)]`), inclusive os de FK, para
 * `doctrine:schema:validate` bater sem depender de hash. Os nomes das FKs seguem a regra do DBAL
 * (`FK_` + crc32 da tabela + crc32 da coluna) — conferidos contra `Version20260910171500`. O
 * comparador do DBAL 4 não compara nome de FK, só de índice.
 *
 * jsonb (não json) em `contexto_resumo` e `pontos`, como `Processo.datajudRaw` e
 * `PublicacaoDjen.payloadDjen`. Timestamps `TIMESTAMP(0) WITHOUT TIME ZONE` como todo o projeto
 * (`datetime_immutable`; a spec dizia timestamptz — seguido o padrão da casa).
 */
final class Version20261006120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'BlueJus IA: cria inteligencia_configuracao e inteligencia_analise e insere as permissões '
            . 'modules.inteligencia.view e admin.inteligencia.manage (idempotente, sem conceder a papéis)';
    }

    public function up(Schema $schema): void
    {
        // --- inteligencia_configuracao -------------------------------------------------------
        $this->addSql('CREATE TABLE inteligencia_configuracao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, habilitada BOOLEAN DEFAULT false NOT NULL, limite_diario INT DEFAULT 50 NOT NULL, limite_mensal INT DEFAULT 500 NOT NULL, mascarar_dados_pessoais BOOLEAN DEFAULT true NOT NULL, consentimento_envio_externo_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, criada_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizada_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, consentimento_por_id INT DEFAULT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_inteligencia_configuracao_tenant ON inteligencia_configuracao (tenant_id)');
        $this->addSql('CREATE INDEX idx_inteligencia_configuracao_consentimento_por ON inteligencia_configuracao (consentimento_por_id)');
        $this->addSql('ALTER TABLE inteligencia_configuracao ADD CONSTRAINT FK_1B057BCB996CC7CE FOREIGN KEY (consentimento_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inteligencia_configuracao ADD CONSTRAINT FK_1B057BCB9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');

        // --- inteligencia_analise ------------------------------------------------------------
        $this->addSql('CREATE TABLE inteligencia_analise (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(20) NOT NULL, provedor VARCHAR(60) DEFAULT NULL, modelo VARCHAR(60) DEFAULT NULL, tokens_entrada INT DEFAULT NULL, tokens_saida INT DEFAULT NULL, duracao_ms INT DEFAULT NULL, tentativas SMALLINT DEFAULT 0 NOT NULL, erro_motivo TEXT DEFAULT NULL, resumo TEXT DEFAULT NULL, pontos JSONB DEFAULT NULL, quem_age VARCHAR(120) DEFAULT NULL, texto_bruto TEXT DEFAULT NULL, interna_do_escritorio BOOLEAN DEFAULT true NOT NULL, lida_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, excluida_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, criada_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, iniciada_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, concluida_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tipo VARCHAR(40) NOT NULL, alvo_tipo VARCHAR(20) NOT NULL, alvo_id INT NOT NULL, versao_do_prompt VARCHAR(40) NOT NULL, contexto_hash VARCHAR(64) NOT NULL, contexto_resumo JSONB NOT NULL, lida_por_id INT DEFAULT NULL, excluida_por_id INT DEFAULT NULL, tenant_id INT NOT NULL, solicitante_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_inteligencia_analise_tenant ON inteligencia_analise (tenant_id)');
        $this->addSql('CREATE INDEX idx_inteligencia_analise_alvo ON inteligencia_analise (tenant_id, alvo_tipo, alvo_id, criada_em)');
        $this->addSql('CREATE INDEX idx_inteligencia_analise_tenant_status ON inteligencia_analise (tenant_id, status)');
        $this->addSql('CREATE INDEX idx_inteligencia_analise_tenant_criada ON inteligencia_analise (tenant_id, criada_em)');
        $this->addSql('CREATE INDEX idx_inteligencia_analise_solicitante ON inteligencia_analise (solicitante_id)');
        $this->addSql('CREATE INDEX idx_inteligencia_analise_lida_por ON inteligencia_analise (lida_por_id)');
        $this->addSql('CREATE INDEX idx_inteligencia_analise_excluida_por ON inteligencia_analise (excluida_por_id)');
        $this->addSql('ALTER TABLE inteligencia_analise ADD CONSTRAINT FK_641CD60D9C9EEA12 FOREIGN KEY (lida_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inteligencia_analise ADD CONSTRAINT FK_641CD60DC39F6355 FOREIGN KEY (excluida_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inteligencia_analise ADD CONSTRAINT FK_641CD60D9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE inteligencia_analise ADD CONSTRAINT FK_641CD60DC680A87 FOREIGN KEY (solicitante_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');

        // --- catálogo de permissões (idempotente, sem conceder a papéis) ---------------------
        $this->addSql(<<<'SQL'
            INSERT INTO permission (code, description, "group")
            SELECT 'modules.inteligencia.view', 'Usar a BlueJus IA', 'modules'
            WHERE NOT EXISTS (SELECT 1 FROM permission WHERE code = 'modules.inteligencia.view')
        SQL);
        $this->addSql(<<<'SQL'
            INSERT INTO permission (code, description, "group")
            SELECT 'admin.inteligencia.manage', 'Configurar a BlueJus IA do escritório', 'admin'
            WHERE NOT EXISTS (SELECT 1 FROM permission WHERE code = 'admin.inteligencia.manage')
        SQL);
    }

    public function down(Schema $schema): void
    {
        // Concessões antes do catálogo (FK tenant_role_permission → permission sem CASCADE).
        $this->addSql(<<<'SQL'
            DELETE FROM tenant_role_permission
            WHERE permission_id IN (
                SELECT id FROM permission WHERE code IN ('modules.inteligencia.view', 'admin.inteligencia.manage')
            )
        SQL);
        $this->addSql("DELETE FROM permission WHERE code IN ('modules.inteligencia.view', 'admin.inteligencia.manage')");

        $this->addSql('ALTER TABLE inteligencia_analise DROP CONSTRAINT FK_641CD60D9C9EEA12');
        $this->addSql('ALTER TABLE inteligencia_analise DROP CONSTRAINT FK_641CD60DC39F6355');
        $this->addSql('ALTER TABLE inteligencia_analise DROP CONSTRAINT FK_641CD60D9033212A');
        $this->addSql('ALTER TABLE inteligencia_analise DROP CONSTRAINT FK_641CD60DC680A87');
        $this->addSql('DROP TABLE inteligencia_analise');

        $this->addSql('ALTER TABLE inteligencia_configuracao DROP CONSTRAINT FK_1B057BCB996CC7CE');
        $this->addSql('ALTER TABLE inteligencia_configuracao DROP CONSTRAINT FK_1B057BCB9033212A');
        $this->addSql('DROP TABLE inteligencia_configuracao');
    }
}
