<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260328183010 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE access_request (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, resource_type VARCHAR(50) NOT NULL, resource_id INT NOT NULL, action VARCHAR(20) NOT NULL, status VARCHAR(20) DEFAULT \'pending\' NOT NULL, requested_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, decided_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, decided_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F3B2558AA76ED395 ON access_request (user_id)');
        $this->addSql('CREATE INDEX IDX_F3B2558AE26B496B ON access_request (decided_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_access_request_pending ON access_request (user_id, resource_type, resource_id, action, status)');
        $this->addSql('ALTER TABLE access_request ADD CONSTRAINT FK_F3B2558AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE access_request ADD CONSTRAINT FK_F3B2558AE26B496B FOREIGN KEY (decided_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE access_request DROP CONSTRAINT FK_F3B2558AA76ED395');
        $this->addSql('ALTER TABLE access_request DROP CONSTRAINT FK_F3B2558AE26B496B');
        $this->addSql('DROP TABLE access_request');
    }
}
