<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425171217 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pasta_observacao_detalhes (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conteudo TEXT NOT NULL, criada_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, editada_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, pasta_id INT NOT NULL, autor_id INT NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_BC5CA27314D45BBE ON pasta_observacao_detalhes (autor_id)');
        $this->addSql('CREATE INDEX idx_pasta_obs_det_pasta_id ON pasta_observacao_detalhes (pasta_id)');
        $this->addSql('CREATE INDEX idx_pasta_obs_det_tenant ON pasta_observacao_detalhes (tenant_id)');
        $this->addSql('ALTER TABLE pasta_observacao_detalhes ADD CONSTRAINT FK_BC5CA2737FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_observacao_detalhes ADD CONSTRAINT FK_BC5CA27314D45BBE FOREIGN KEY (autor_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_observacao_detalhes ADD CONSTRAINT FK_BC5CA2739033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pasta_observacao_detalhes DROP CONSTRAINT FK_BC5CA2737FCDBC8C');
        $this->addSql('ALTER TABLE pasta_observacao_detalhes DROP CONSTRAINT FK_BC5CA27314D45BBE');
        $this->addSql('ALTER TABLE pasta_observacao_detalhes DROP CONSTRAINT FK_BC5CA2739033212A');
        $this->addSql('DROP TABLE pasta_observacao_detalhes');
    }
}
