<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Sync Fase 2 — cria a tabela `sync_drive_conexao` (entidade {@see \App\Sync\Entity\TenantDriveConexao}):
 * a conexão do Google Drive por escritório ("Conectar meu Drive"). Uma linha por tenant (índice único em
 * tenant_id), guarda o refresh_token OAuth CIFRADO em repouso e a pasta-raiz do acervo daquele escritório.
 *
 * DDL literal, gerado a partir do metadata Doctrine (schema:update --dump-sql). Sem data-migration:
 * a permissão reusa `admin.tenant.settings.manage` (já no catálogo), então nada a inserir em `permission`.
 */
final class Version20260714130000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Sync Fase 2 — cria sync_drive_conexao (conexão do Drive por tenant, refresh_token cifrado).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE sync_drive_conexao (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                refresh_token_cifrado TEXT NOT NULL,
                root_folder_id VARCHAR(255) DEFAULT NULL,
                conta_email VARCHAR(255) DEFAULT NULL,
                escopo VARCHAR(255) DEFAULT NULL,
                ativo BOOLEAN DEFAULT false NOT NULL,
                conectado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                tenant_id INT NOT NULL,
                conectado_por_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE UNIQUE INDEX UNIQ_A4E00A799033212A ON sync_drive_conexao (tenant_id)');
        $this->addSql('CREATE INDEX IDX_A4E00A794A3D5F4 ON sync_drive_conexao (conectado_por_id)');
        $this->addSql('ALTER TABLE sync_drive_conexao ADD CONSTRAINT FK_A4E00A799033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE sync_drive_conexao ADD CONSTRAINT FK_A4E00A794A3D5F4 FOREIGN KEY (conectado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE sync_drive_conexao');
    }
}
