<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260507153912 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE user_tenant (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, codigo_funcionario VARCHAR(20) DEFAULT NULL, data_admissao DATE DEFAULT NULL, demitido_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, last_login_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, is_active BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_role_id INT DEFAULT NULL, cargo_id INT DEFAULT NULL, lotacao_id INT DEFAULT NULL, user_id INT NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2B0BDF5FC4956098 ON user_tenant (tenant_role_id)');
        $this->addSql('CREATE INDEX IDX_2B0BDF5F813AC380 ON user_tenant (cargo_id)');
        $this->addSql('CREATE INDEX IDX_2B0BDF5F7E27C2B8 ON user_tenant (lotacao_id)');
        $this->addSql('CREATE INDEX idx_user_tenant_user_id ON user_tenant (user_id)');
        $this->addSql('CREATE INDEX idx_user_tenant_tenant_id ON user_tenant (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_user_tenant ON user_tenant (user_id, tenant_id)');
        $this->addSql('ALTER TABLE user_tenant ADD CONSTRAINT FK_2B0BDF5FC4956098 FOREIGN KEY (tenant_role_id) REFERENCES tenant_role (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_tenant ADD CONSTRAINT FK_2B0BDF5F813AC380 FOREIGN KEY (cargo_id) REFERENCES cargo (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_tenant ADD CONSTRAINT FK_2B0BDF5F7E27C2B8 FOREIGN KEY (lotacao_id) REFERENCES lotacao (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_tenant ADD CONSTRAINT FK_2B0BDF5FA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE user_tenant ADD CONSTRAINT FK_2B0BDF5F9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE user_tenant DROP CONSTRAINT FK_2B0BDF5FC4956098');
        $this->addSql('ALTER TABLE user_tenant DROP CONSTRAINT FK_2B0BDF5F813AC380');
        $this->addSql('ALTER TABLE user_tenant DROP CONSTRAINT FK_2B0BDF5F7E27C2B8');
        $this->addSql('ALTER TABLE user_tenant DROP CONSTRAINT FK_2B0BDF5FA76ED395');
        $this->addSql('ALTER TABLE user_tenant DROP CONSTRAINT FK_2B0BDF5F9033212A');
        $this->addSql('DROP TABLE user_tenant');
    }
}
