<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709154458 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cobranças Etapa 4 — acordos: cria cobranca_acordo (escopada por tenant) e ALTERA '
            . 'cobranca_obrigacao adicionando acordo_origem_id (parcela gerada) e acordo_substituto_id '
            . '(obrigação substituída — nunca apagada, invariável 14), ambos FK nullable ON DELETE SET NULL.';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cobranca_acordo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, status VARCHAR(255) NOT NULL, data_acordo DATE NOT NULL, motivo_rompimento VARCHAR(255) DEFAULT NULL, motivo_cancelamento VARCHAR(255) DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, caso_id INT NOT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FFD7C69E9033212A ON cobranca_acordo (tenant_id)');
        $this->addSql('CREATE INDEX IDX_FFD7C69EA0AD3491 ON cobranca_acordo (caso_id)');
        $this->addSql('CREATE INDEX IDX_FFD7C69EF42F4A03 ON cobranca_acordo (criado_por_id)');
        $this->addSql('CREATE INDEX idx_cobranca_acordo_tenant_caso ON cobranca_acordo (tenant_id, caso_id)');
        $this->addSql('ALTER TABLE cobranca_acordo ADD CONSTRAINT FK_FFD7C69E9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_acordo ADD CONSTRAINT FK_FFD7C69EA0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_acordo ADD CONSTRAINT FK_FFD7C69EF42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_obrigacao ADD acordo_origem_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cobranca_obrigacao ADD acordo_substituto_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE cobranca_obrigacao ADD CONSTRAINT FK_AAAEF147EFB94708 FOREIGN KEY (acordo_origem_id) REFERENCES cobranca_acordo (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_obrigacao ADD CONSTRAINT FK_AAAEF147DF2C4D6D FOREIGN KEY (acordo_substituto_id) REFERENCES cobranca_acordo (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_AAAEF147EFB94708 ON cobranca_obrigacao (acordo_origem_id)');
        $this->addSql('CREATE INDEX IDX_AAAEF147DF2C4D6D ON cobranca_obrigacao (acordo_substituto_id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cobranca_acordo DROP CONSTRAINT FK_FFD7C69E9033212A');
        $this->addSql('ALTER TABLE cobranca_acordo DROP CONSTRAINT FK_FFD7C69EA0AD3491');
        $this->addSql('ALTER TABLE cobranca_acordo DROP CONSTRAINT FK_FFD7C69EF42F4A03');
        $this->addSql('DROP TABLE cobranca_acordo');
        $this->addSql('ALTER TABLE cobranca_obrigacao DROP CONSTRAINT FK_AAAEF147EFB94708');
        $this->addSql('ALTER TABLE cobranca_obrigacao DROP CONSTRAINT FK_AAAEF147DF2C4D6D');
        $this->addSql('DROP INDEX IDX_AAAEF147EFB94708');
        $this->addSql('DROP INDEX IDX_AAAEF147DF2C4D6D');
        $this->addSql('ALTER TABLE cobranca_obrigacao DROP acordo_origem_id');
        $this->addSql('ALTER TABLE cobranca_obrigacao DROP acordo_substituto_id');
    }
}
