<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Foto diária do estoque do Dashboard (`dashboard_foto`): metas ativas, demandas ativas, metas
 * vencidas e prazos próximos de cada colaborador no fim de cada dia, gravada pelo comando
 * `app:dashboard:fotografar`. É o que permite a tendência dessas quatro colunas — que não dá
 * para reconstruir do passado — comparando com a foto de `data_de − 1 dia`.
 *
 * Escrita à mão (não por `make:migration`), com os nomes do mapeamento de
 * `App\Dashboard\Entity\DashboardFoto`: índice e unique declarados lá; FKs pelo hash padrão do
 * DBAL (`FK_` + crc32 da tabela e da coluna), para o `doctrine:schema:validate` não propor nada.
 *
 * Anatomia das FKs:
 *   - `user_id` CASCADE: a foto não sobrevive ao usuário;
 *   - `tenant_id` sem ação (padrão): a purga do escritório apaga explicitamente
 *     (`PurgarEscritorioUseCase::ORDEM_DELECAO`).
 *
 * Os índices implícitos de FK não são criados: `tenant_id` é coberto pelo unique
 * `(tenant_id, user_id, referencia)` e `user_id` por `idx_dashboard_foto_user`.
 */
final class Version20261006171500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria dashboard_foto: foto diária do estoque do Dashboard por colaborador';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE dashboard_foto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, referencia DATE NOT NULL, metas_ativas INT NOT NULL, demandas_ativas INT NOT NULL, metas_vencidas INT NOT NULL, prazos_proximos INT NOT NULL, tenant_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_dashboard_foto_user ON dashboard_foto (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_dashboard_foto_tenant_user_ref ON dashboard_foto (tenant_id, user_id, referencia)');
        $this->addSql('ALTER TABLE dashboard_foto ADD CONSTRAINT FK_FDAC54E79033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE dashboard_foto ADD CONSTRAINT FK_FDAC54E7A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE dashboard_foto DROP CONSTRAINT FK_FDAC54E79033212A');
        $this->addSql('ALTER TABLE dashboard_foto DROP CONSTRAINT FK_FDAC54E7A76ED395');
        $this->addSql('DROP TABLE dashboard_foto');
    }
}
