<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Preferências pessoais de tela: o ajuste que o usuário faz no menu ⋮ da tabela Desempenho do
 * Dashboard (densidade, animações, setas de tendência, colunas ocultas — desenho
 * "01 - Dashboard 1.2.2", "Personalização por usuário"). Uma linha por (escritório, usuário,
 * chave); o valor é JSON validado no servidor contra uma lista fechada.
 *
 * Escrita à mão (não por `make:migration`), com os nomes que o Doctrine derivaria do mapeamento
 * de `App\Dashboard\Entity\PreferenciaDoUsuario`: índice e unique declarados lá; FKs pelo hash
 * padrão do DBAL (`FK_` + crc32 da tabela e da coluna), para o `doctrine:schema:validate` não
 * propor nada.
 *
 * Anatomia das FKs:
 *   - `user_id` CASCADE: preferência pessoal; some com o usuário;
 *   - `tenant_id` sem ação (padrão): a purga do escritório apaga explicitamente
 *     (`PurgarEscritorioUseCase::ORDEM_DELECAO`).
 *
 * Índices: `tenant_id` é coberto pelo unique (tenant_id, user_id, chave), que também é o árbitro
 * do `INSERT … ON CONFLICT` da gravação; `user_id` tem índice próprio.
 */
final class Version20261006161500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria preferencia_usuario: ajustes pessoais de tela por usuário e escritório';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE preferencia_usuario (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, chave VARCHAR(80) NOT NULL, valor JSON NOT NULL, tenant_id INT NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_preferencia_usuario_user ON preferencia_usuario (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_preferencia_usuario_tenant_user_chave ON preferencia_usuario (tenant_id, user_id, chave)');
        $this->addSql('ALTER TABLE preferencia_usuario ADD CONSTRAINT FK_B73556859033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE preferencia_usuario ADD CONSTRAINT FK_B7355685A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE preferencia_usuario DROP CONSTRAINT FK_B73556859033212A');
        $this->addSql('ALTER TABLE preferencia_usuario DROP CONSTRAINT FK_B7355685A76ED395');
        $this->addSql('DROP TABLE preferencia_usuario');
    }
}
