<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260415191758 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE cliente_documento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, categoria VARCHAR(40) NOT NULL, descricao TEXT DEFAULT NULL, caminho_arquivo VARCHAR(255) NOT NULL, nome_original VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, tamanho_bytes INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, numero VARCHAR(255) DEFAULT NULL, cliente_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A1BCA103DE734E51 ON cliente_documento (cliente_id)');
        $this->addSql('ALTER TABLE cliente_documento ADD CONSTRAINT FK_A1BCA103DE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE cliente_documento DROP CONSTRAINT FK_A1BCA103DE734E51');
        $this->addSql('DROP TABLE cliente_documento');
    }
}
