<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Espelho da contabilidade — Fase 0 (docs/specs/cobranca-espelho-da-contabilidade.md §4.2).
 *
 * Cria as três tabelas que guardam cada relatório da contabilidade como ele veio: o lote
 * (`cobranca_relatorio_importado`), cada linha do arquivo (`cobranca_relatorio_linha`) e o rodapé
 * somado da própria planilha (`cobranca_relatorio_totalizador`).
 *
 * **Puramente aditiva.** Nenhuma tabela existente é tocada, nenhuma linha de dado de dívida é
 * escrita ou alterada. Isso é normativo na spec (§3), não conveniência.
 *
 * ESCRITA À MÃO, não gerada — pelo mesmo motivo da `Version20260730120000`: o `make:migration` roda
 * contra o banco do dev e propõe dropar índices funcionais criados por SQL cru. Antes de escrever,
 * fotografei `doctrine:schema:update --dump-sql` e encontrei 6 comandos de ruído pré-existente:
 * três `DROP INDEX` (`idx_cobranca_pessoa_tenant_cnpj_digitos`,
 * `idx_cobranca_pessoa_tenant_cpf_digitos` e `uniq_cobranca_obrigacao_ref_competencia`) e três
 * `ALTER ... DROP DEFAULT` em `cobranca_pessoa_{telefone,email,endereco}`. **Nenhum deles entra
 * aqui.** Aceitar o `DROP` do `uniq_cobranca_obrigacao_ref_competencia` seria especialmente grave:
 * é o índice único em que a conferência (§5.2) apoia a chave de ligação, e sem ele entra dívida
 * duplicada em silêncio.
 */
final class Version20260812160000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Espelho da contabilidade: lote, linhas e totalizador do relatório importado';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE cobranca_relatorio_importado (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                tipo VARCHAR(20) NOT NULL,
                arquivo_nome VARCHAR(255) NOT NULL,
                arquivo_hash VARCHAR(64) NOT NULL,
                emitido_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                dados_ate DATE DEFAULT NULL,
                config_declarada JSON DEFAULT NULL,
                unidades_declaradas INT DEFAULT NULL,
                linhas_total INT NOT NULL,
                linhas_dados INT NOT NULL,
                linhas_totalizador INT NOT NULL,
                versao_leitor INT NOT NULL,
                lido_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                tenant_id INT NOT NULL,
                carteira_id INT NOT NULL,
                lido_por_id INT DEFAULT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX IDX_4778E9E79033212A ON cobranca_relatorio_importado (tenant_id)');
        $this->addSql('CREATE INDEX IDX_4778E9E75265899 ON cobranca_relatorio_importado (carteira_id)');
        $this->addSql('CREATE INDEX IDX_4778E9E78914F820 ON cobranca_relatorio_importado (lido_por_id)');
        $this->addSql('CREATE INDEX idx_cobranca_relatorio_tenant_carteira ON cobranca_relatorio_importado (tenant_id, carteira_id)');
        $this->addSql('CREATE INDEX idx_cobranca_relatorio_dados_ate ON cobranca_relatorio_importado (dados_ate)');

        // A idempotência da leitura. `versao_leitor` faz parte da chave de propósito: sem ela,
        // "corrigiu o leitor? relê e gera lote novo" (§4.4) seria recusado pelo próprio índice,
        // porque o mesmo arquivo tem sempre o mesmo hash.
        $this->addSql(<<<'SQL'
            CREATE UNIQUE INDEX uniq_cobranca_relatorio_arquivo
                ON cobranca_relatorio_importado (tenant_id, carteira_id, arquivo_hash, versao_leitor)
        SQL);

        $this->addSql(<<<'SQL'
            CREATE TABLE cobranca_relatorio_linha (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                numero_linha INT NOT NULL,
                bloco VARCHAR(20) NOT NULL,
                unidade VARCHAR(255) DEFAULT NULL,
                sacado VARCHAR(255) DEFAULT NULL,
                nn VARCHAR(50) DEFAULT NULL,
                classe VARCHAR(255) DEFAULT NULL,
                competencia VARCHAR(20) DEFAULT NULL,
                vencimento DATE DEFAULT NULL,
                atraso INT DEFAULT NULL,
                valor INT DEFAULT NULL,
                juros INT DEFAULT NULL,
                multa INT DEFAULT NULL,
                correcao INT DEFAULT NULL,
                honorarios INT DEFAULT NULL,
                total INT DEFAULT NULL,
                acordo_texto TEXT DEFAULT NULL,
                recebimento VARCHAR(255) DEFAULT NULL,
                bruto JSON DEFAULT NULL,
                tenant_id INT NOT NULL,
                relatorio_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX IDX_49B3DE5F9033212A ON cobranca_relatorio_linha (tenant_id)');
        $this->addSql('CREATE INDEX idx_cobranca_relatorio_linha_relatorio ON cobranca_relatorio_linha (relatorio_id)');
        $this->addSql('CREATE INDEX idx_cobranca_relatorio_linha_bloco ON cobranca_relatorio_linha (relatorio_id, bloco)');
        $this->addSql('CREATE INDEX idx_cobranca_relatorio_linha_nn ON cobranca_relatorio_linha (relatorio_id, nn, competencia)');
        $this->addSql('CREATE INDEX idx_cobranca_relatorio_linha_unidade ON cobranca_relatorio_linha (relatorio_id, unidade)');

        $this->addSql(<<<'SQL'
            CREATE TABLE cobranca_relatorio_totalizador (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                numero_linha INT NOT NULL,
                forma VARCHAR(20) NOT NULL,
                rotulo VARCHAR(255) NOT NULL,
                valor INT DEFAULT NULL,
                juros INT DEFAULT NULL,
                multa INT DEFAULT NULL,
                correcao INT DEFAULT NULL,
                honorarios INT DEFAULT NULL,
                total INT DEFAULT NULL,
                tenant_id INT NOT NULL,
                relatorio_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);

        $this->addSql('CREATE INDEX IDX_58BD58519033212A ON cobranca_relatorio_totalizador (tenant_id)');
        $this->addSql('CREATE INDEX idx_cobranca_relatorio_totalizador_relatorio ON cobranca_relatorio_totalizador (relatorio_id)');

        $this->addSql(<<<'SQL'
            ALTER TABLE cobranca_relatorio_importado
                ADD CONSTRAINT FK_4778E9E79033212A FOREIGN KEY (tenant_id)
                REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE cobranca_relatorio_importado
                ADD CONSTRAINT FK_4778E9E75265899 FOREIGN KEY (carteira_id)
                REFERENCES cobranca_carteira (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE cobranca_relatorio_importado
                ADD CONSTRAINT FK_4778E9E78914F820 FOREIGN KEY (lido_por_id)
                REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE cobranca_relatorio_linha
                ADD CONSTRAINT FK_49B3DE5F9033212A FOREIGN KEY (tenant_id)
                REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE cobranca_relatorio_linha
                ADD CONSTRAINT FK_49B3DE5F6F8D7380 FOREIGN KEY (relatorio_id)
                REFERENCES cobranca_relatorio_importado (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);

        $this->addSql(<<<'SQL'
            ALTER TABLE cobranca_relatorio_totalizador
                ADD CONSTRAINT FK_58BD58519033212A FOREIGN KEY (tenant_id)
                REFERENCES tenant (id) NOT DEFERRABLE
        SQL);
        $this->addSql(<<<'SQL'
            ALTER TABLE cobranca_relatorio_totalizador
                ADD CONSTRAINT FK_58BD58516F8D7380 FOREIGN KEY (relatorio_id)
                REFERENCES cobranca_relatorio_importado (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        // O espelho é derivado: cada lote pode ser reconstruído relendo o arquivo original. Derrubar
        // as três tabelas não perde nada que não se recupere, e não toca em dado de dívida.
        $this->addSql('DROP TABLE IF EXISTS cobranca_relatorio_linha');
        $this->addSql('DROP TABLE IF EXISTS cobranca_relatorio_totalizador');
        $this->addSql('DROP TABLE IF EXISTS cobranca_relatorio_importado');
    }
}
