<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Cria ponto_lancamento_horas_pagas: ajuste manual do banco de horas, preso a uma competência
 * (ano/mês), com sinal (positivo acrescenta, negativo desconta) e sem tenant_id nulo — dado de ponto.
 *
 * O arquivo gerado pelo `make:migration` veio com bem mais RUÍDO de base do que apenas 6 statements
 * cosméticos: um `--dump-sql` fotografado ANTES de gerar (na própria worktree desta frente) mostrou
 * ~90 linhas de divergência preexistente entre o mapeamento do código e o schema real do dev
 * compartilhado — nada disso é desta frente. Removido daqui: `CREATE TABLE indice_monetario` (já tem
 * migration própria, `Version20260729142925`, só ainda não aplicada neste dev); toda a renomeação
 * `objeto_id`→`caso_id` em 8 tabelas de Cobranca (`cobranca_acordo`, `cobranca_documento`,
 * `cobranca_evento_historico`, `cobranca_liquidacao`, `cobranca_obrigacao`, `cobranca_pagamento`,
 * `cobranca_proxima_acao`, `cobranca_secao`) com seus `DROP`/`CREATE` de FK e índice; a coluna nova
 * `cobranca_obrigacao.referencia_externa`; o `DROP TABLE cobranca_obrigacao_identidade_externa`; a
 * remoção de `cobranca_objeto.pasta_judicial_id`; a coluna `cobranca_pessoa_telefone.tipo`; os 2
 * `DROP INDEX` em índices funcionais de `cobranca_pessoa` (idx_..._cnpj_digitos/_cpf_digitos, que o
 * Doctrine não sabe representar no mapeamento); os `ALTER ... ALTER atual DROP DEFAULT` em
 * telefone/email/endereço de `cobranca_pessoa`; e o `DROP INDEX
 * uniq_cobranca_vinculo_principal_por_objeto` + `cobranca_vinculo_pessoa_objeto DROP principal`.
 * Tudo isso já tem (ou terá) migration própria de outra frente — `doctrine:migrations:status` mostra
 * `Version20260728160000` e `Version20260729142925` como "not migrated" neste dev, e é exatamente daí
 * que vem esse ruído.
 */
final class Version20260730143805 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria ponto_lancamento_horas_pagas (ajuste manual do banco de horas por competência)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE ponto_lancamento_horas_pagas (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, ano SMALLINT NOT NULL, mes SMALLINT NOT NULL, minutos INT NOT NULL, motivo TEXT NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, user_id INT NOT NULL, criado_por_id INT NOT NULL, atualizado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_105706079033212A ON ponto_lancamento_horas_pagas (tenant_id)');
        $this->addSql('CREATE INDEX IDX_10570607A76ED395 ON ponto_lancamento_horas_pagas (user_id)');
        $this->addSql('CREATE INDEX IDX_10570607F42F4A03 ON ponto_lancamento_horas_pagas (criado_por_id)');
        $this->addSql('CREATE INDEX IDX_105706078447AA9A ON ponto_lancamento_horas_pagas (atualizado_por_id)');
        $this->addSql('CREATE INDEX IDX_HORAS_PAGAS_COMPETENCIA ON ponto_lancamento_horas_pagas (tenant_id, user_id, ano, mes)');
        $this->addSql('ALTER TABLE ponto_lancamento_horas_pagas ADD CONSTRAINT FK_105706079033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ponto_lancamento_horas_pagas ADD CONSTRAINT FK_10570607A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ponto_lancamento_horas_pagas ADD CONSTRAINT FK_10570607F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE ponto_lancamento_horas_pagas ADD CONSTRAINT FK_105706078447AA9A FOREIGN KEY (atualizado_por_id) REFERENCES "user" (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE ponto_lancamento_horas_pagas DROP CONSTRAINT FK_105706079033212A');
        $this->addSql('ALTER TABLE ponto_lancamento_horas_pagas DROP CONSTRAINT FK_10570607A76ED395');
        $this->addSql('ALTER TABLE ponto_lancamento_horas_pagas DROP CONSTRAINT FK_10570607F42F4A03');
        $this->addSql('ALTER TABLE ponto_lancamento_horas_pagas DROP CONSTRAINT FK_105706078447AA9A');
        $this->addSql('DROP TABLE ponto_lancamento_horas_pagas');
    }
}
