<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Tabela global de índices oficiais (INPC, IPCA e taxa legal da Lei 14.905/2024) que alimenta a
 * calculadora de atualização monetária do "Simular acordo".
 *
 * ⚠️ **Sem `tenant_id`, de propósito** (spec §7.1): índice oficial de inflação é dado público,
 * idêntico para todo escritório. É a única exceção do projeto à regra de isolamento multi-tenant.
 *
 * O arquivo gerado pelo `make:migration` vinha com 6 statements de RUÍDO de base, fotografados
 * antes de gerar (`doctrine:schema:update --dump-sql`) e removidos daqui: 3 `DROP INDEX` de índices
 * FUNCIONAIS de cobrança (o Doctrine não sabe representá-los no mapeamento e propõe apagá-los — o
 * `down()` chegava a recriá-los errado, como índice simples em `tenant_id`) e 3 `DROP DEFAULT` em
 * colunas `atual` de contato. Nada disso é desta frente.
 */
final class Version20260729142925 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria indice_monetario (tabela global de índices oficiais do BCB, sem tenant_id).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE indice_monetario (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                serie VARCHAR(20) NOT NULL,
                competencia DATE NOT NULL,
                variacao_pct NUMERIC(12, 6) NOT NULL,
                fonte VARCHAR(40) NOT NULL,
                importado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                PRIMARY KEY (id)
            )
            SQL);

        // Serve de guarda contra duplicata E de índice das duas consultas quentes (série inteira em
        // ordem, e última competência publicada da série).
        $this->addSql('CREATE UNIQUE INDEX uniq_indice_monetario_serie_competencia ON indice_monetario (serie, competencia)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE indice_monetario');
    }
}
