<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222163000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE parte_processo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, processo_id INT NOT NULL, tipo VARCHAR(30) NOT NULL, nome VARCHAR(255) NOT NULL, documento VARCHAR(30) DEFAULT NULL, papel VARCHAR(30) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_4F9726C5D3F49B91 ON parte_processo (processo_id)');
        $this->addSql('CREATE TABLE movimentacao_processo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, processo_id INT NOT NULL, data_movimentacao DATE DEFAULT NULL, descricao VARCHAR(255) NOT NULL, tipo VARCHAR(100) DEFAULT NULL, orgao VARCHAR(100) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_E5FCB8A7D3F49B91 ON movimentacao_processo (processo_id)');
        $this->addSql('ALTER TABLE parte_processo ADD CONSTRAINT FK_4F9726C5D3F49B91 FOREIGN KEY (processo_id) REFERENCES processo (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE movimentacao_processo ADD CONSTRAINT FK_E5FCB8A7D3F49B91 FOREIGN KEY (processo_id) REFERENCES processo (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE processo DROP COLUMN partes');
        $this->addSql('ALTER TABLE processo DROP COLUMN movimentacoes');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE processo ADD partes JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE processo ADD movimentacoes JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE parte_processo DROP CONSTRAINT FK_4F9726C5D3F49B91');
        $this->addSql('ALTER TABLE movimentacao_processo DROP CONSTRAINT FK_E5FCB8A7D3F49B91');
        $this->addSql('DROP TABLE parte_processo');
        $this->addSql('DROP TABLE movimentacao_processo');
    }
}
