<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Ajuste 4 dos Cobranças: remove a feature "Revisão de pessoa cobrada" por completo.
 * Dropa a tabela cobranca_revisao_pessoa_cobrada (idempotente com IF EXISTS). O down() recria a tabela
 * espelhando o DDL da Version20260709191327 (que a criou), preservando reversibilidade.
 */
final class Version20260713120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Remove a tabela cobranca_revisao_pessoa_cobrada (feature Revisão de pessoa cobrada removida)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE IF EXISTS cobranca_revisao_pessoa_cobrada');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cobranca_revisao_pessoa_cobrada (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, motivo VARCHAR(255) NOT NULL, status VARCHAR(255) NOT NULL, resolucao TEXT DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, resolvida_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, caso_id INT NOT NULL, criado_por_id INT DEFAULT NULL, resolvida_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_310C3B489033212A ON cobranca_revisao_pessoa_cobrada (tenant_id)');
        $this->addSql('CREATE INDEX IDX_310C3B48A0AD3491 ON cobranca_revisao_pessoa_cobrada (caso_id)');
        $this->addSql('CREATE INDEX IDX_310C3B48F42F4A03 ON cobranca_revisao_pessoa_cobrada (criado_por_id)');
        $this->addSql('CREATE INDEX IDX_310C3B48EC51598A ON cobranca_revisao_pessoa_cobrada (resolvida_por_id)');
        $this->addSql('CREATE INDEX idx_cobranca_revisao_tenant_caso ON cobranca_revisao_pessoa_cobrada (tenant_id, caso_id)');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada ADD CONSTRAINT FK_310C3B489033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada ADD CONSTRAINT FK_310C3B48A0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada ADD CONSTRAINT FK_310C3B48F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_revisao_pessoa_cobrada ADD CONSTRAINT FK_310C3B48EC51598A FOREIGN KEY (resolvida_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }
}
