<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260701214019 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Home office no ponto: tabela home_office_config (config por user+tenant) e flag home_office em registro_ponto';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE home_office_config (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, dias_semana JSON NOT NULL, datas_avulsas JSON NOT NULL, vigencia_inicio DATE DEFAULT NULL, vigencia_fim DATE DEFAULT NULL, ativo BOOLEAN NOT NULL, user_id INT NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_2484376AA76ED395 ON home_office_config (user_id)');
        $this->addSql('CREATE INDEX IDX_2484376A9033212A ON home_office_config (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_home_office_user_tenant ON home_office_config (user_id, tenant_id)');
        $this->addSql('ALTER TABLE home_office_config ADD CONSTRAINT FK_2484376AA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE home_office_config ADD CONSTRAINT FK_2484376A9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        // DEFAULT false: backfilla os registros existentes e mantém inserts sem a coluna funcionando
        // (o mapeamento declara options.default => false, então schema:validate fica em sync).
        $this->addSql('ALTER TABLE registro_ponto ADD home_office BOOLEAN NOT NULL DEFAULT false');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE home_office_config DROP CONSTRAINT FK_2484376AA76ED395');
        $this->addSql('ALTER TABLE home_office_config DROP CONSTRAINT FK_2484376A9033212A');
        $this->addSql('DROP TABLE home_office_config');
        $this->addSql('ALTER TABLE registro_ponto DROP home_office');
    }
}
