<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260502115703 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE parte_contraria DROP CONSTRAINT fk_aa4d4a217fcdbc8c');
        $this->addSql('DROP TABLE parte_contraria');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE parte_contraria (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, pasta_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_aa4d4a217fcdbc8c ON parte_contraria (pasta_id)');
        $this->addSql('ALTER TABLE parte_contraria ADD CONSTRAINT fk_aa4d4a217fcdbc8c FOREIGN KEY (pasta_id) REFERENCES pasta (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }
}
