<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260709215805 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cobranças Etapa 6 — documentos do Caso: cria cobranca_secao (organização opcional dos '
            . 'documentos) e cobranca_documento (arquivo anexado ao Caso, SEM depender de Pasta — invariável '
            . '25), ambas escopadas por tenant. FKs caso_id/secao_id ON DELETE CASCADE; arquivo físico isolado '
            . 'por tenant em cobrancas/<tenantId>/ (padrão M5).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cobranca_documento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, categoria VARCHAR(255) NOT NULL, descricao TEXT DEFAULT NULL, caminho_arquivo VARCHAR(255) NOT NULL, nome_original VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, tamanho_bytes INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, ordem INT DEFAULT 0 NOT NULL, caso_id INT NOT NULL, secao_id INT DEFAULT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FCFCD5604E04F226 ON cobranca_documento (secao_id)');
        $this->addSql('CREATE INDEX idx_cobranca_documento_caso ON cobranca_documento (caso_id)');
        $this->addSql('CREATE INDEX idx_cobranca_documento_tenant ON cobranca_documento (tenant_id)');
        $this->addSql('CREATE TABLE cobranca_secao (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, ordem INT DEFAULT 0 NOT NULL, criada_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, caso_id INT NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_cobranca_secao_caso ON cobranca_secao (caso_id)');
        $this->addSql('CREATE INDEX idx_cobranca_secao_tenant ON cobranca_secao (tenant_id)');
        $this->addSql('ALTER TABLE cobranca_documento ADD CONSTRAINT FK_FCFCD560A0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_documento ADD CONSTRAINT FK_FCFCD5604E04F226 FOREIGN KEY (secao_id) REFERENCES cobranca_secao (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_documento ADD CONSTRAINT FK_FCFCD5609033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_secao ADD CONSTRAINT FK_17AA64D0A0AD3491 FOREIGN KEY (caso_id) REFERENCES cobranca_caso (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_secao ADD CONSTRAINT FK_17AA64D09033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cobranca_documento DROP CONSTRAINT FK_FCFCD560A0AD3491');
        $this->addSql('ALTER TABLE cobranca_documento DROP CONSTRAINT FK_FCFCD5604E04F226');
        $this->addSql('ALTER TABLE cobranca_documento DROP CONSTRAINT FK_FCFCD5609033212A');
        $this->addSql('ALTER TABLE cobranca_secao DROP CONSTRAINT FK_17AA64D0A0AD3491');
        $this->addSql('ALTER TABLE cobranca_secao DROP CONSTRAINT FK_17AA64D09033212A');
        $this->addSql('DROP TABLE cobranca_documento');
        $this->addSql('DROP TABLE cobranca_secao');
    }
}
