<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260223121500 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria tabela de chat de mensagens da tarefa';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tarefa_mensagem (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tarefa_id INT NOT NULL, usuario_id INT NOT NULL, mensagem TEXT NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_TAREFA_MENSAGEM_TAREFA ON tarefa_mensagem (tarefa_id)');
        $this->addSql('CREATE INDEX IDX_TAREFA_MENSAGEM_USUARIO ON tarefa_mensagem (usuario_id)');
        $this->addSql('ALTER TABLE tarefa_mensagem ADD CONSTRAINT FK_TAREFA_MENSAGEM_TAREFA FOREIGN KEY (tarefa_id) REFERENCES tarefa (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tarefa_mensagem ADD CONSTRAINT FK_TAREFA_MENSAGEM_USUARIO FOREIGN KEY (usuario_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE tarefa_mensagem DROP CONSTRAINT FK_TAREFA_MENSAGEM_TAREFA');
        $this->addSql('ALTER TABLE tarefa_mensagem DROP CONSTRAINT FK_TAREFA_MENSAGEM_USUARIO');
        $this->addSql('DROP TABLE tarefa_mensagem');
    }
}
