<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Cria `redefinicao_senha` — pedidos de recuperação de senha (F1 da spec
 * `docs/specs/abertura-cadastro-publico.md`).
 *
 * Escrita à mão, não gerada: o `--dump-sql` deste ambiente traz junto três `DROP INDEX`
 * de índice funcional (que o mapeamento Doctrine não sabe representar) e três
 * `ALTER ... DROP DEFAULT` de outra frente ainda não aplicada. Nada disso é desta
 * entrega e nada disso entra aqui.
 *
 * O `token_hash` guarda o SHA-256 do token enviado por e-mail, nunca o token em claro:
 * este link destrava conta existente, então vazamento do banco não pode virar tomada de
 * conta. `ON DELETE CASCADE` porque pedido de redefinição não sobrevive ao usuário.
 */
final class Version20260805120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria a tabela redefinicao_senha (recuperação de senha por e-mail)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql(<<<'SQL'
            CREATE TABLE redefinicao_senha (
                id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
                usado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL,
                token_hash VARCHAR(64) NOT NULL,
                expira_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                ip VARCHAR(45) NOT NULL,
                user_agent VARCHAR(255) DEFAULT NULL,
                criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL,
                user_id INT NOT NULL,
                PRIMARY KEY (id)
            )
        SQL);
        $this->addSql('CREATE INDEX idx_redefinicao_senha_user ON redefinicao_senha (user_id)');
        $this->addSql('CREATE UNIQUE INDEX uq_redefinicao_senha_token_hash ON redefinicao_senha (token_hash)');
        $this->addSql(<<<'SQL'
            ALTER TABLE redefinicao_senha
                ADD CONSTRAINT FK_5025AFCDA76ED395 FOREIGN KEY (user_id)
                REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE
        SQL);
    }

    public function down(Schema $schema): void
    {
        $this->addSql('DROP TABLE redefinicao_senha');
    }
}
