<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260401000000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Módulo Ponto Eletrônico: tabelas sede, escala_trabalho, feriado, justificativa_ponto, registro_ponto';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE sede (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, latitude NUMERIC(10, 8) NOT NULL, longitude NUMERIC(11, 8) NOT NULL, raio_permitido INT NOT NULL, timezone VARCHAR(50) NOT NULL, ssids_autorizados JSON DEFAULT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_SEDE_TENANT ON sede (tenant_id)');
        $this->addSql('CREATE TABLE escala_trabalho (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, entrada1 VARCHAR(5) DEFAULT NULL, saida1 VARCHAR(5) DEFAULT NULL, entrada2 VARCHAR(5) DEFAULT NULL, saida2 VARCHAR(5) DEFAULT NULL, carga_horaria_diaria INT NOT NULL, dias_semana JSON NOT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_ESCALA_USER ON escala_trabalho (user_id)');
        $this->addSql('CREATE TABLE feriado (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, data DATE NOT NULL, recorrente BOOLEAN NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_FERIADO_TENANT ON feriado (tenant_id)');
        $this->addSql('CREATE TABLE justificativa_ponto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data DATE NOT NULL, descricao TEXT NOT NULL, anexo_path VARCHAR(255) DEFAULT NULL, status VARCHAR(20) NOT NULL, data_analise TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, observacao_analise TEXT DEFAULT NULL, user_id INT NOT NULL, analisado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_JUST_USER ON justificativa_ponto (user_id)');
        $this->addSql('CREATE INDEX IDX_JUST_ANALISADOR ON justificativa_ponto (analisado_por_id)');
        $this->addSql('CREATE TABLE registro_ponto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, data_hora TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, latitude NUMERIC(10, 8) NOT NULL, longitude NUMERIC(11, 8) NOT NULL, precisao_gps NUMERIC(10, 2) NOT NULL, ssid VARCHAR(255) DEFAULT NULL, tipo VARCHAR(20) NOT NULL, observacao TEXT DEFAULT NULL, user_id INT NOT NULL, sede_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_REGISTRO_USER ON registro_ponto (user_id)');
        $this->addSql('CREATE INDEX IDX_REGISTRO_SEDE ON registro_ponto (sede_id)');
        $this->addSql('ALTER TABLE sede ADD CONSTRAINT FK_SEDE_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE escala_trabalho ADD CONSTRAINT FK_ESCALA_USER FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE feriado ADD CONSTRAINT FK_FERIADO_TENANT FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE justificativa_ponto ADD CONSTRAINT FK_JUST_USER FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE justificativa_ponto ADD CONSTRAINT FK_JUST_ANALISADOR FOREIGN KEY (analisado_por_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registro_ponto ADD CONSTRAINT FK_REGISTRO_USER FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE registro_ponto ADD CONSTRAINT FK_REGISTRO_SEDE FOREIGN KEY (sede_id) REFERENCES sede (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE registro_ponto DROP CONSTRAINT FK_REGISTRO_SEDE');
        $this->addSql('ALTER TABLE registro_ponto DROP CONSTRAINT FK_REGISTRO_USER');
        $this->addSql('ALTER TABLE justificativa_ponto DROP CONSTRAINT FK_JUST_ANALISADOR');
        $this->addSql('ALTER TABLE justificativa_ponto DROP CONSTRAINT FK_JUST_USER');
        $this->addSql('ALTER TABLE feriado DROP CONSTRAINT FK_FERIADO_TENANT');
        $this->addSql('ALTER TABLE escala_trabalho DROP CONSTRAINT FK_ESCALA_USER');
        $this->addSql('ALTER TABLE sede DROP CONSTRAINT FK_SEDE_TENANT');
        $this->addSql('DROP TABLE registro_ponto');
        $this->addSql('DROP TABLE justificativa_ponto');
        $this->addSql('DROP TABLE feriado');
        $this->addSql('DROP TABLE escala_trabalho');
        $this->addSql('DROP TABLE sede');
    }
}
