<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260324124920 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE parte_contraria (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, pasta_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_AA4D4A217FCDBC8C ON parte_contraria (pasta_id)');
        $this->addSql('CREATE TABLE pasta (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nup VARCHAR(255) NOT NULL, status VARCHAR(20) DEFAULT \'ativo\' NOT NULL, data_abertura TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, descricao TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, processo_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9B3BBC81BF45C3B7 ON pasta (nup)');
        $this->addSql('CREATE INDEX IDX_9B3BBC81AAA822D2 ON pasta (processo_id)');
        $this->addSql('CREATE TABLE pasta_cliente (pasta_id INT NOT NULL, cliente_id INT NOT NULL, PRIMARY KEY (pasta_id, cliente_id))');
        $this->addSql('CREATE INDEX IDX_307B3BA77FCDBC8C ON pasta_cliente (pasta_id)');
        $this->addSql('CREATE INDEX IDX_307B3BA7DE734E51 ON pasta_cliente (cliente_id)');
        $this->addSql('CREATE TABLE pasta_documento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, categoria VARCHAR(20) NOT NULL, descricao TEXT DEFAULT NULL, caminho_arquivo VARCHAR(255) NOT NULL, nome_original VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, tamanho_bytes INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pasta_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_69D2B3817FCDBC8C ON pasta_documento (pasta_id)');
        $this->addSql('ALTER TABLE parte_contraria ADD CONSTRAINT FK_AA4D4A217FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta ADD CONSTRAINT FK_9B3BBC81AAA822D2 FOREIGN KEY (processo_id) REFERENCES processo (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_cliente ADD CONSTRAINT FK_307B3BA77FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pasta_cliente ADD CONSTRAINT FK_307B3BA7DE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE pasta_documento ADD CONSTRAINT FK_69D2B3817FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE parte_contraria DROP CONSTRAINT FK_AA4D4A217FCDBC8C');
        $this->addSql('ALTER TABLE pasta DROP CONSTRAINT FK_9B3BBC81AAA822D2');
        $this->addSql('ALTER TABLE pasta_cliente DROP CONSTRAINT FK_307B3BA77FCDBC8C');
        $this->addSql('ALTER TABLE pasta_cliente DROP CONSTRAINT FK_307B3BA7DE734E51');
        $this->addSql('ALTER TABLE pasta_documento DROP CONSTRAINT FK_69D2B3817FCDBC8C');
        $this->addSql('DROP TABLE parte_contraria');
        $this->addSql('DROP TABLE pasta');
        $this->addSql('DROP TABLE pasta_cliente');
        $this->addSql('DROP TABLE pasta_documento');
    }
}
