<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260425182419 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE pasta_checklist_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, concluido BOOLEAN DEFAULT false NOT NULL, ordem INT DEFAULT 0 NOT NULL, pasta_id INT NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_pasta_checklist_item_pasta ON pasta_checklist_item (pasta_id)');
        $this->addSql('CREATE INDEX idx_pasta_checklist_item_tenant ON pasta_checklist_item (tenant_id)');
        $this->addSql('ALTER TABLE pasta_checklist_item ADD CONSTRAINT FK_4D4318C07FCDBC8C FOREIGN KEY (pasta_id) REFERENCES pasta (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_checklist_item ADD CONSTRAINT FK_4D4318C09033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE pasta_checklist_item DROP CONSTRAINT FK_4D4318C07FCDBC8C');
        $this->addSql('ALTER TABLE pasta_checklist_item DROP CONSTRAINT FK_4D4318C09033212A');
        $this->addSql('DROP TABLE pasta_checklist_item');
    }
}
