<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260408180237 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function preUp(Schema $schema): void
    {
        $this->skipIf(
            !$schema->hasTable('checklist_item_cliente'),
            'Tabelas de checklist/documento não existem neste banco — migration de reestruturação ignorada.'
        );
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE checklist_item_cliente DROP CONSTRAINT fk_f58e285de734e51');
        $this->addSql('ALTER TABLE checklist_item_cliente DROP CONSTRAINT fk_f58e285f6939175');
        $this->addSql('ALTER TABLE checklist_item_pasta DROP CONSTRAINT fk_11e3728e7fcdbc8c');
        $this->addSql('ALTER TABLE checklist_item_pasta DROP CONSTRAINT fk_11e3728ef6939175');
        $this->addSql('ALTER TABLE documento_cliente DROP CONSTRAINT fk_21a44bd3de734e51');
        $this->addSql('ALTER TABLE documento_cliente DROP CONSTRAINT fk_21a44bd3f6939175');
        $this->addSql('ALTER TABLE pasta_documento DROP CONSTRAINT fk_69d2b381f6939175');
        $this->addSql('DROP INDEX idx_69d2b381f6939175');
        $this->addSql('ALTER TABLE pasta_documento DROP tipo_documento_id');
        $this->addSql('ALTER TABLE tipo_documento DROP CONSTRAINT fk_54df91899033212a');
        $this->addSql('DROP TABLE checklist_item_cliente');
        $this->addSql('DROP TABLE checklist_item_pasta');
        $this->addSql('DROP TABLE documento_cliente');
        $this->addSql('DROP TABLE tipo_documento');
        $this->addSql('ALTER TABLE cliente_pf DROP necessita_gratuidade_justica');
        $this->addSql('ALTER TABLE pasta ADD doc_procuracao_ok BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE pasta ADD doc_identificacao_ok BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE pasta ADD doc_comprovante_residencia_ok BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE pasta ADD doc_gratuidade_justica_ok BOOLEAN DEFAULT false NOT NULL');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE checklist_item_cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label_custom VARCHAR(255) DEFAULT NULL, marcado_manualmente BOOLEAN DEFAULT false NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cliente_id INT NOT NULL, tipo_documento_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_f58e285f6939175 ON checklist_item_cliente (tipo_documento_id)');
        $this->addSql('CREATE INDEX idx_f58e285de734e51 ON checklist_item_cliente (cliente_id)');
        $this->addSql('CREATE TABLE checklist_item_pasta (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, label VARCHAR(255) DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, pasta_id INT NOT NULL, label_custom VARCHAR(255) DEFAULT NULL, marcado_manualmente BOOLEAN DEFAULT false NOT NULL, tipo_documento_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_11e3728ef6939175 ON checklist_item_pasta (tipo_documento_id)');
        $this->addSql('CREATE INDEX idx_11e3728e7fcdbc8c ON checklist_item_pasta (pasta_id)');
        $this->addSql('CREATE TABLE documento_cliente (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, categoria VARCHAR(50) NOT NULL, titulo VARCHAR(255) NOT NULL, nome_original VARCHAR(255) NOT NULL, caminho_arquivo VARCHAR(255) NOT NULL, mime_type VARCHAR(100) NOT NULL, tamanho_bytes INT NOT NULL, uploaded_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, cliente_id INT NOT NULL, descricao VARCHAR(500) DEFAULT NULL, tipo_documento_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_21a44bd3de734e51 ON documento_cliente (cliente_id)');
        $this->addSql('CREATE INDEX idx_21a44bd3f6939175 ON documento_cliente (tipo_documento_id)');
        $this->addSql('CREATE TABLE tipo_documento (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, slug VARCHAR(100) NOT NULL, classificacao VARCHAR(10) NOT NULL, ativo BOOLEAN DEFAULT true NOT NULL, ordem_exibicao INT DEFAULT 0 NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_54df91899033212a ON tipo_documento (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_tipo_doc_slug_tenant ON tipo_documento (slug, tenant_id)');
        $this->addSql('ALTER TABLE checklist_item_cliente ADD CONSTRAINT fk_f58e285de734e51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checklist_item_cliente ADD CONSTRAINT fk_f58e285f6939175 FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checklist_item_pasta ADD CONSTRAINT fk_11e3728e7fcdbc8c FOREIGN KEY (pasta_id) REFERENCES pasta (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE checklist_item_pasta ADD CONSTRAINT fk_11e3728ef6939175 FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE documento_cliente ADD CONSTRAINT fk_21a44bd3de734e51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE documento_cliente ADD CONSTRAINT fk_21a44bd3f6939175 FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE tipo_documento ADD CONSTRAINT fk_54df91899033212a FOREIGN KEY (tenant_id) REFERENCES tenant (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE cliente_pf ADD necessita_gratuidade_justica BOOLEAN DEFAULT false NOT NULL');
        $this->addSql('ALTER TABLE pasta DROP doc_procuracao_ok');
        $this->addSql('ALTER TABLE pasta DROP doc_identificacao_ok');
        $this->addSql('ALTER TABLE pasta DROP doc_comprovante_residencia_ok');
        $this->addSql('ALTER TABLE pasta DROP doc_gratuidade_justica_ok');
        $this->addSql('ALTER TABLE pasta_documento ADD tipo_documento_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE pasta_documento ADD CONSTRAINT fk_69d2b381f6939175 FOREIGN KEY (tipo_documento_id) REFERENCES tipo_documento (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('CREATE INDEX idx_69d2b381f6939175 ON pasta_documento (tipo_documento_id)');
    }
}
