<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260708210509 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cobranças Etapa 1 — núcleo de cadastro: tabelas cobranca_carteira, cobranca_objeto, '
            . 'cobranca_pessoa e cobranca_vinculo_pessoa_objeto (todas escopadas por tenant).';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE cobranca_carteira (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, modo VARCHAR(255) NOT NULL, forma_honorarios VARCHAR(255) NOT NULL, percentual_honorarios NUMERIC(5, 2) DEFAULT NULL, tolerancia_atraso_dias INT DEFAULT 0 NOT NULL, tipo_vinculo_preferido VARCHAR(255) DEFAULT NULL, rotulo_objeto VARCHAR(50) DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, cliente_id INT NOT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A2238EE59033212A ON cobranca_carteira (tenant_id)');
        $this->addSql('CREATE INDEX IDX_A2238EE5DE734E51 ON cobranca_carteira (cliente_id)');
        $this->addSql('CREATE INDEX IDX_A2238EE5F42F4A03 ON cobranca_carteira (criado_por_id)');
        $this->addSql('CREATE TABLE cobranca_objeto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, identificacao VARCHAR(255) NOT NULL, descricao TEXT DEFAULT NULL, referencia_externa VARCHAR(255) DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, carteira_id INT NOT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_9CC8D9C89033212A ON cobranca_objeto (tenant_id)');
        $this->addSql('CREATE INDEX IDX_9CC8D9C85265899 ON cobranca_objeto (carteira_id)');
        $this->addSql('CREATE INDEX IDX_9CC8D9C8F42F4A03 ON cobranca_objeto (criado_por_id)');
        $this->addSql('CREATE TABLE cobranca_pessoa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(255) NOT NULL, cpf VARCHAR(14) DEFAULT NULL, cnpj VARCHAR(18) DEFAULT NULL, email VARCHAR(255) DEFAULT NULL, telefone VARCHAR(20) DEFAULT NULL, observacao TEXT DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_A75C94DC9033212A ON cobranca_pessoa (tenant_id)');
        $this->addSql('CREATE INDEX IDX_A75C94DCF42F4A03 ON cobranca_pessoa (criado_por_id)');
        $this->addSql('CREATE TABLE cobranca_vinculo_pessoa_objeto (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tipo_vinculo VARCHAR(255) NOT NULL, data_inicio DATE NOT NULL, data_fim DATE DEFAULT NULL, motivo_encerramento VARCHAR(255) DEFAULT NULL, observacao TEXT DEFAULT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, atualizado_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, pessoa_id INT NOT NULL, objeto_id INT NOT NULL, criado_por_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9E05EA49033212A ON cobranca_vinculo_pessoa_objeto (tenant_id)');
        $this->addSql('CREATE INDEX IDX_F9E05EA4DF6FA0A5 ON cobranca_vinculo_pessoa_objeto (pessoa_id)');
        $this->addSql('CREATE INDEX IDX_F9E05EA476F5CD27 ON cobranca_vinculo_pessoa_objeto (objeto_id)');
        $this->addSql('CREATE INDEX IDX_F9E05EA4F42F4A03 ON cobranca_vinculo_pessoa_objeto (criado_por_id)');
        $this->addSql('ALTER TABLE cobranca_carteira ADD CONSTRAINT FK_A2238EE59033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_carteira ADD CONSTRAINT FK_A2238EE5DE734E51 FOREIGN KEY (cliente_id) REFERENCES cliente (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_carteira ADD CONSTRAINT FK_A2238EE5F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_objeto ADD CONSTRAINT FK_9CC8D9C89033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_objeto ADD CONSTRAINT FK_9CC8D9C85265899 FOREIGN KEY (carteira_id) REFERENCES cobranca_carteira (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_objeto ADD CONSTRAINT FK_9CC8D9C8F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_pessoa ADD CONSTRAINT FK_A75C94DC9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_pessoa ADD CONSTRAINT FK_A75C94DCF42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_vinculo_pessoa_objeto ADD CONSTRAINT FK_F9E05EA49033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_vinculo_pessoa_objeto ADD CONSTRAINT FK_F9E05EA4DF6FA0A5 FOREIGN KEY (pessoa_id) REFERENCES cobranca_pessoa (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_vinculo_pessoa_objeto ADD CONSTRAINT FK_F9E05EA476F5CD27 FOREIGN KEY (objeto_id) REFERENCES cobranca_objeto (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE cobranca_vinculo_pessoa_objeto ADD CONSTRAINT FK_F9E05EA4F42F4A03 FOREIGN KEY (criado_por_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE cobranca_carteira DROP CONSTRAINT FK_A2238EE59033212A');
        $this->addSql('ALTER TABLE cobranca_carteira DROP CONSTRAINT FK_A2238EE5DE734E51');
        $this->addSql('ALTER TABLE cobranca_carteira DROP CONSTRAINT FK_A2238EE5F42F4A03');
        $this->addSql('ALTER TABLE cobranca_objeto DROP CONSTRAINT FK_9CC8D9C89033212A');
        $this->addSql('ALTER TABLE cobranca_objeto DROP CONSTRAINT FK_9CC8D9C85265899');
        $this->addSql('ALTER TABLE cobranca_objeto DROP CONSTRAINT FK_9CC8D9C8F42F4A03');
        $this->addSql('ALTER TABLE cobranca_pessoa DROP CONSTRAINT FK_A75C94DC9033212A');
        $this->addSql('ALTER TABLE cobranca_pessoa DROP CONSTRAINT FK_A75C94DCF42F4A03');
        $this->addSql('ALTER TABLE cobranca_vinculo_pessoa_objeto DROP CONSTRAINT FK_F9E05EA49033212A');
        $this->addSql('ALTER TABLE cobranca_vinculo_pessoa_objeto DROP CONSTRAINT FK_F9E05EA4DF6FA0A5');
        $this->addSql('ALTER TABLE cobranca_vinculo_pessoa_objeto DROP CONSTRAINT FK_F9E05EA476F5CD27');
        $this->addSql('ALTER TABLE cobranca_vinculo_pessoa_objeto DROP CONSTRAINT FK_F9E05EA4F42F4A03');
        $this->addSql('DROP TABLE cobranca_carteira');
        $this->addSql('DROP TABLE cobranca_objeto');
        $this->addSql('DROP TABLE cobranca_pessoa');
        $this->addSql('DROP TABLE cobranca_vinculo_pessoa_objeto');
    }
}
