<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260223120000 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria tabelas de tarefas e atribuicoes com vinculo opcional a processo';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE tarefa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, processo_id INT DEFAULT NULL, titulo VARCHAR(255) NOT NULL, descricao TEXT NOT NULL, prazo TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, status VARCHAR(20) NOT NULL, data_criacao TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_conclusao TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, arquivos_admin JSON DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5A86847FAA822D2 ON tarefa (processo_id)');
        $this->addSql("ALTER TABLE tarefa ADD CONSTRAINT CHK_TAREFA_STATUS CHECK (status IN ('pendente','em_revisao','concluida','reaberta'))");
        $this->addSql('ALTER TABLE tarefa ADD CONSTRAINT FK_5A86847FAA822D2 FOREIGN KEY (processo_id) REFERENCES processo (id) ON DELETE SET NULL NOT DEFERRABLE');

        $this->addSql('CREATE TABLE atribuicao_tarefa (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, tarefa_id INT NOT NULL, usuario_id INT NOT NULL, status VARCHAR(20) NOT NULL, data_atribuicao TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, data_envio_revisao TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, arquivos_usuario JSON DEFAULT NULL, descricao_resposta TEXT DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E3005EFAA822D2 ON atribuicao_tarefa (tarefa_id)');
        $this->addSql('CREATE INDEX IDX_5E3005EFFB88E14F ON atribuicao_tarefa (usuario_id)');
        $this->addSql("ALTER TABLE atribuicao_tarefa ADD CONSTRAINT CHK_ATRIBUICAO_STATUS CHECK (status IN ('pendente','em_revisao','concluida'))");
        $this->addSql('ALTER TABLE atribuicao_tarefa ADD CONSTRAINT FK_5E3005EFAA822D2 FOREIGN KEY (tarefa_id) REFERENCES tarefa (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE atribuicao_tarefa ADD CONSTRAINT FK_5E3005EFFB88E14F FOREIGN KEY (usuario_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE atribuicao_tarefa DROP CONSTRAINT FK_5E3005EFAA822D2');
        $this->addSql('ALTER TABLE atribuicao_tarefa DROP CONSTRAINT FK_5E3005EFFB88E14F');
        $this->addSql('ALTER TABLE tarefa DROP CONSTRAINT FK_5A86847FAA822D2');
        $this->addSql('DROP TABLE atribuicao_tarefa');
        $this->addSql('DROP TABLE tarefa');
    }
}
