<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Modelos de checklist de documentos da pasta: a lista salva com um nome, para reaplicar
 * em outras pastas.
 *
 * As duas tabelas pendem do TENANT (não da pasta), que é o que permite montar o modelo
 * numa pasta e usá-lo em outra. `pasta_checklist_modelo_item` cai por CASCADE do modelo.
 *
 * O que o `make:migration` propôs e foi RETIRADO daqui (ruído pré-existente do dev,
 * conferido antes com `doctrine:schema:update --dump-sql`, e nada disso é desta frente):
 *   - DROP de `uniq_cobranca_obrigacao_ref_competencia`, `idx_cobranca_pessoa_tenant_cpf_digitos`
 *     e `idx_cobranca_pessoa_tenant_cnpj_digitos` — índices funcionais criados por SQL cru, que o
 *     Doctrine não sabe representar no mapeamento e por isso propõe apagar a cada geração. O
 *     primeiro é UNIQUE e é ele que impede dívida duplicada; apagá-lo não quebra nada visível.
 *   - `ALTER … ALTER atual DROP DEFAULT` em cobranca_pessoa_{email,endereco,telefone}, de outra
 *     frente ainda não aplicada no dev.
 */
final class Version20260901153507 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria as tabelas de modelo de checklist de documentos da pasta';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE pasta_checklist_modelo (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, nome VARCHAR(120) NOT NULL, criado_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, tenant_id INT NOT NULL, autor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_B7049A9E14D45BBE ON pasta_checklist_modelo (autor_id)');
        $this->addSql('CREATE INDEX idx_pasta_checklist_modelo_tenant ON pasta_checklist_modelo (tenant_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_pasta_checklist_modelo_tenant_nome ON pasta_checklist_modelo (tenant_id, nome)');
        $this->addSql('CREATE TABLE pasta_checklist_modelo_item (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titulo VARCHAR(255) NOT NULL, ordem INT DEFAULT 0 NOT NULL, modelo_id INT NOT NULL, tenant_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_pasta_checklist_modelo_item_modelo ON pasta_checklist_modelo_item (modelo_id)');
        $this->addSql('CREATE INDEX idx_pasta_checklist_modelo_item_tenant ON pasta_checklist_modelo_item (tenant_id)');
        $this->addSql('ALTER TABLE pasta_checklist_modelo ADD CONSTRAINT FK_B7049A9E9033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_checklist_modelo ADD CONSTRAINT FK_B7049A9E14D45BBE FOREIGN KEY (autor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_checklist_modelo_item ADD CONSTRAINT FK_52785D17C3A9576E FOREIGN KEY (modelo_id) REFERENCES pasta_checklist_modelo (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE pasta_checklist_modelo_item ADD CONSTRAINT FK_52785D179033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE pasta_checklist_modelo_item DROP CONSTRAINT FK_52785D17C3A9576E');
        $this->addSql('ALTER TABLE pasta_checklist_modelo_item DROP CONSTRAINT FK_52785D179033212A');
        $this->addSql('ALTER TABLE pasta_checklist_modelo DROP CONSTRAINT FK_B7049A9E9033212A');
        $this->addSql('ALTER TABLE pasta_checklist_modelo DROP CONSTRAINT FK_B7049A9E14D45BBE');
        $this->addSql('DROP TABLE pasta_checklist_modelo_item');
        $this->addSql('DROP TABLE pasta_checklist_modelo');
    }
}
