<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Nota técnica: o texto do advogado sobre um PROCESSO, opcionalmente pendurado numa
 * movimentação do Push Processual (desenho 1.2.3, decisão do dono em 2026-10-05).
 *
 * Anatomia das FKs, cada uma com um porquê:
 *   - `processo_id` CASCADE: a nota é DO processo; some com ele.
 *   - `publicacao_djen_id` SET NULL: a publicação é só o gancho — se ela for removida (ex.:
 *     ressincronização), a nota continua no processo, sem o gancho.
 *   - `autor_id` SET NULL: desvincular o colaborador do escritório não apaga o que ele escreveu
 *     sobre o caso.
 *   - `tenant_id` NOT NULL: a entidade é TenantAware e passa pelo TenantFilter.
 *
 * O que o `make:migration` propôs e foi RETIRADO daqui (ruído pré-existente do dev, fotografado
 * ANTES com `doctrine:schema:update --dump-sql` no master, e nada disso é desta frente):
 *   - DROP de `uniq_cobranca_obrigacao_ref_competencia`, `idx_cobranca_pessoa_tenant_cpf_digitos`
 *     e `idx_cobranca_pessoa_tenant_cnpj_digitos` — índices funcionais criados por SQL cru, que o
 *     Doctrine não sabe representar no mapeamento e por isso propõe apagar a cada geração. O
 *     primeiro é UNIQUE e é ele que impede dívida duplicada.
 *   - `ALTER … ALTER atual DROP DEFAULT` em cobranca_pessoa_{email,endereco,telefone}, de outra
 *     frente ainda não aplicada no dev.
 */
final class Version20261006002519 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Cria nota_tecnica: nota do advogado sobre o processo, opcionalmente ligada a uma publicação do DJEN';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE nota_tecnica (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, conteudo TEXT NOT NULL, criada_em TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, editada_em TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, tenant_id INT NOT NULL, processo_id INT NOT NULL, publicacao_djen_id INT DEFAULT NULL, autor_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_3730349114D45BBE ON nota_tecnica (autor_id)');
        $this->addSql('CREATE INDEX idx_nota_tecnica_tenant ON nota_tecnica (tenant_id)');
        $this->addSql('CREATE INDEX idx_nota_tecnica_processo ON nota_tecnica (processo_id)');
        $this->addSql('CREATE INDEX idx_nota_tecnica_publicacao ON nota_tecnica (publicacao_djen_id)');
        $this->addSql('ALTER TABLE nota_tecnica ADD CONSTRAINT FK_373034919033212A FOREIGN KEY (tenant_id) REFERENCES tenant (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE nota_tecnica ADD CONSTRAINT FK_37303491AAA822D2 FOREIGN KEY (processo_id) REFERENCES processo (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE nota_tecnica ADD CONSTRAINT FK_373034919874CB0A FOREIGN KEY (publicacao_djen_id) REFERENCES publicacao_djen (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE nota_tecnica ADD CONSTRAINT FK_3730349114D45BBE FOREIGN KEY (autor_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE nota_tecnica DROP CONSTRAINT FK_373034919033212A');
        $this->addSql('ALTER TABLE nota_tecnica DROP CONSTRAINT FK_37303491AAA822D2');
        $this->addSql('ALTER TABLE nota_tecnica DROP CONSTRAINT FK_373034919874CB0A');
        $this->addSql('ALTER TABLE nota_tecnica DROP CONSTRAINT FK_3730349114D45BBE');
        $this->addSql('DROP TABLE nota_tecnica');
    }
}
