server {
    listen 80;
    server_name connect.bluejus.com.br;
    server_tokens off;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name connect.bluejus.com.br;
    server_tokens off;
    client_max_body_size 70m;

    ssl_certificate     /etc/letsencrypt/live/connect.bluejus.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/connect.bluejus.com.br/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;

    location / {
        resolver 127.0.0.11 valid=10s;
        set $bluejus_connect_upstream http://bluejus_connect_api_prod:3333;
        proxy_pass $bluejus_connect_upstream;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 120s;
    }
}
