controllers:
    resource: ../../src/Controller/
    type: attribute

profile_controllers:
    resource: ../../src/Profile/Controller/
    type: attribute

ponto_controllers:
    resource: ../../src/Ponto/Controller/
    type: attribute
