doctrine:
    dbal:
        driver: 'pdo_pgsql'
        url: '%env(resolve:DATABASE_URL)%'

        # Configuração da versão do servidor PostgreSQL
        server_version: '15.0'

        profiling_collect_backtrace: '%kernel.debug%'
        use_savepoints: true
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        filters:
            tenant:
                class: App\Shared\Doctrine\Filter\TenantFilter
                enabled: false
        mappings:
            App:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            AppCliente:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Cliente/Entity'
                prefix: 'App\Cliente\Entity'
                alias: AppCliente
            AppProcesso:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Processo/Entity'
                prefix: 'App\Processo\Entity'
                alias: AppProcesso
            AppExpediente:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Expediente/Entity'
                prefix: 'App\Expediente\Entity'
                alias: AppExpediente
            AppProfile:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Profile/Entity'
                prefix: 'App\Profile\Entity'
                alias: AppProfile
            AppKanban:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Kanban/Entity'
                prefix: 'App\Kanban\Entity'
                alias: AppKanban
            AppPasta:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Pasta/Entity'
                prefix: 'App\Pasta\Entity'
                alias: AppPasta
            AppTermo:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Termo/Entity'
                prefix: 'App\Termo\Entity'
                alias: AppTermo
            AppPonto:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Ponto/Entity'
                prefix: 'App\Ponto\Entity'
                alias: AppPonto
            AppAuth:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Auth/Entity'
                prefix: 'App\Auth\Entity'
                alias: AppAuth
        controller_resolver:
            auto_mapping: false
        dql:
            numeric_functions:
                CAST_INT: App\Shared\Doctrine\DQL\CastInteger

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
