# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    default_locale: pt_BR

    translator:
        default_path: '%kernel.project_dir%/translations'
        fallbacks:
            - pt_BR
            - pt
            - en

    rate_limiter:
        login:
            policy: sliding_window
            limit: 5
            interval: '15 minutes'

    # Note that the session will be started ONLY if you read or write from it.
    session: true

    #esi: true
    #fragments: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
